<?php

return [
	'show'  => true,
	'title' => 'Promocje',
	'cards' => [
		[
			'layout'       => 'media',
			'area'         => 'a',
			'color'        => 'peach',
			'color_custom' => '',
			'badge'        => 'Czesne · I stopień',
			'badge_bg'     => '#ffc862',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-student-hoodie.jpg',
			'promo_id'     => 'szybki',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Zniżka proporcjonalnie w obu semestrach roku akademickiego 2026/2027',
			'meta'         => '',
			'link'         => '/oferta/?promo=szybki',
		],
		[
			'layout'       => 'solid',
			'area'         => 'b',
			'color'        => 'pink',
			'color_custom' => '',
			'badge'        => 'Czesne · PL i EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'promo_id'     => 'jednorazowo',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Semestr z góry −5% · rok z góry −10%',
			'meta'         => '',
			'link'         => '/oferta/?promo=jednorazowo',
		],
		[
			'layout'       => 'media',
			'area'         => 'c',
			'color'        => 'lilac',
			'color_custom' => '',
			'badge'        => 'Czesne · Warszawa · I st.',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-student-paint.jpg',
			'promo_id'     => 'techart',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Tegoroczny maturzysta · profil na świadectwie',
			'meta'         => '',
			'link'         => '/oferta/?promo=techart',
		],
		[
			'layout'       => 'media',
			'area'         => 'd',
			'color'        => 'sky',
			'color_custom' => '',
			'badge'        => 'Czesne · I i II stopień',
			'badge_bg'     => '#c8dff2',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-students-grass.jpg',
			'promo_id'     => 'grupie',
			'sub'          => '400',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Zniżka proporcjonalnie w obu semestrach roku akademickiego 2026/2027',
			'meta'         => '',
			'link'         => '/oferta/?promo=grupie&sub=400',
		],
		[
			'layout'       => 'solid',
			'area'         => 'e',
			'color'        => 'lime',
			'color_custom' => '',
			'badge'        => 'Czesne · PL i EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'headline'     => 'Wpisowe gratis <strong>0 zł</strong>',
			'value'        => '',
			'text'         => 'zamiast 490 zł · przy zapisie do 30.10.2026',
			'meta'         => '',
			'link'         => '/kalkulator-czesnego/?rekr=kurs',
		],
		[
			'layout'       => 'solid',
			'area'         => 'f',
			'color'        => 'apricot',
			'color_custom' => '',
			'badge'        => 'Czesne · PL i EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'promo_id'     => 'przejscie',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Przeniesienie z innej uczelni · semestr startu',
			'meta'         => '',
			'link'         => '/oferta/?promo=przejscie',
		],
	],
];
