<?php

/**
 * Ukrainian defaults for homepage promotions section.
 *
 * @return array<string, mixed>
 */
return [
	'show'  => true,
	'title' => 'Акції',
	'cards' => [
		[
			'layout'       => 'media',
			'area'         => 'a',
			'color'        => 'peach',
			'color_custom' => '',
			'badge'        => 'Внесок за навчання · I ступінь',
			'badge_bg'     => '#ffc862',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-student-hoodie.jpg',
			'headline'     => 'Навчання на крок ближче, <strong>на 1 000 zł дешевше</strong>',
			'value'        => '',
			'text'         => 'Знижка пропорційно в обох семестрах навчального року 2026/2027',
			'meta'         => 'Реєстрація до 30.09 · договір до 30.10.2026',
			'link'         => '/kalkulator-czesnego/?promo=szybki',
		],
		[
			'layout'       => 'solid',
			'area'         => 'b',
			'color'        => 'pink',
			'color_custom' => '',
			'badge'        => 'Внесок за навчання · PL і EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'headline'     => 'Оплата наперед',
			'value'        => '−5% / −10%',
			'text'         => 'Семестр наперед −5% · рік наперед −10%',
			'meta'         => 'Термін: до 10 вересня',
			'link'         => '/kalkulator-czesnego/?promo=jednorazowo',
		],
		[
			'layout'       => 'media',
			'area'         => 'c',
			'color'        => 'lilac',
			'color_custom' => '',
			'badge'        => 'Внесок за навчання · Варшава · I ст.',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-student-paint.jpg',
			'headline'     => 'Випускник школи<br><strong>технічної/мистецької</strong>',
			'value'        => '− 1 200 zł',
			'text'         => 'Цьогорічний випускник · профіль у свідоцтві',
			'meta'         => '',
			'link'         => '/kalkulator-czesnego/?promo=techart',
		],
		[
			'layout'       => 'media',
			'area'         => 'd',
			'color'        => 'sky',
			'color_custom' => '',
			'badge'        => 'Внесок за навчання · I і II ступінь',
			'badge_bg'     => '#c8dff2',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-students-grass.jpg',
			'headline'     => '<strong>В групі дешевше</strong>',
			'value'        => '−400 zł',
			'text'         => 'Знижка пропорційно в обох семестрах навчального року 2026/2027',
			'meta'         => 'Групи 5+ осіб · 2–4 особи −200 zł · до 30.09',
			'link'         => '/kalkulator-czesnego/?promo=grupie&sub=400',
		],
		[
			'layout'       => 'solid',
			'area'         => 'e',
			'color'        => 'lime',
			'color_custom' => '',
			'badge'        => 'Внесок за навчання · PL і EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'headline'     => 'Вступний внесок <strong>0 zł</strong>',
			'value'        => '',
			'text'         => 'замість 490 zł · при записі до 30.10.2026',
			'meta'         => '',
			'link'         => '/kalkulator-czesnego/?rekr=kurs',
		],
		[
			'layout'       => 'solid',
			'area'         => 'f',
			'color'        => 'apricot',
			'color_custom' => '',
			'badge'        => 'Внесок за навчання · PL і EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'headline'     => 'Перехід до ATA',
			'value'        => '−30%',
			'text'         => 'Переведення з іншого ВНЗ · семестр старту',
			'meta'         => '',
			'link'         => '/kalkulator-czesnego/?promo=przejscie',
		],
	],
];
