<?php

/**
 * English defaults for homepage promotions section.
 *
 * @return array<string, mixed>
 */
return [
	'show'  => true,
	'title' => 'Promotions',
	'cards' => [
		[
			'layout'       => 'media',
			'area'         => 'a',
			'color'        => 'peach',
			'color_custom' => '',
			'badge'        => 'Tuition · Bachelor\'s',
			'badge_bg'     => '#ffc862',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-student-hoodie.jpg',
			'promo_id'     => 'szybki',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Discount applied proportionally across both semesters of the 2026/2027 academic year',
			'meta'         => '',
			'link'         => '/oferta/?promo=szybki',
		],
		[
			'layout'       => 'solid',
			'area'         => 'b',
			'color'        => 'pink',
			'color_custom' => '',
			'badge'        => 'Tuition · PL & EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'promo_id'     => 'jednorazowo',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Semester in advance −5% · year in advance −10%',
			'meta'         => '',
			'link'         => '/oferta/?promo=jednorazowo',
		],
		[
			'layout'       => 'media',
			'area'         => 'c',
			'color'        => 'lilac',
			'color_custom' => '',
			'badge'        => 'Tuition · Warsaw · Bachelor\'s',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-student-paint.jpg',
			'promo_id'     => 'techart',
			'headline'     => '',
			'value'        => '',
			'text'         => 'This year\'s secondary-school graduate · profile on the diploma',
			'meta'         => '',
			'link'         => '/oferta/?promo=techart',
		],
		[
			'layout'       => 'media',
			'area'         => 'd',
			'color'        => 'sky',
			'color_custom' => '',
			'badge'        => 'Tuition · 1st & 2nd cycle',
			'badge_bg'     => '#c8dff2',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-students-grass.jpg',
			'promo_id'     => 'grupie',
			'sub'          => '400',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Discount applied proportionally across both semesters of the 2026/2027 academic year',
			'meta'         => '',
			'link'         => '/oferta/?promo=grupie&sub=400',
		],
		[
			'layout'       => 'solid',
			'area'         => 'e',
			'color'        => 'lime',
			'color_custom' => '',
			'badge'        => 'Tuition · PL & EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'headline'     => 'Enrolment fee waived <strong>PLN 0</strong>',
			'value'        => '',
			'text'         => 'instead of PLN 490 · when you enrol by 30 Oct 2026',
			'meta'         => '',
			'link'         => '/oferta/',
		],
		[
			'layout'       => 'solid',
			'area'         => 'f',
			'color'        => 'apricot',
			'color_custom' => '',
			'badge'        => 'Tuition · PL & EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'promo_id'     => 'przejscie',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Transfer from another university · starting semester',
			'meta'         => '',
			'link'         => '/oferta/?promo=przejscie',
		],
	],
];
