<?php

/**
 * English defaults for homepage promotions section.
 *
 * @return array<string, mixed>
 */
return [
	'show'  => true,
	'title' => 'Promotions',
	'cards' => [
		[
			'layout'       => 'media',
			'area'         => 'a',
			'color'        => 'peach',
			'color_custom' => '',
			'badge'        => 'Tuition · Bachelor\'s',
			'badge_bg'     => '#ffc862',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-student-hoodie.jpg',
			'headline'     => 'One step closer to studying, <strong>PLN 1,000 less</strong>',
			'value'        => '',
			'text'         => 'Discount applied proportionally across both semesters of the 2026/2027 academic year',
			'meta'         => 'Register by 30 Aug · contract by 30 Sep 2026',
			'link'         => '/kalkulator-czesnego/?promo=szybki',
		],
		[
			'layout'       => 'solid',
			'area'         => 'b',
			'color'        => 'pink',
			'color_custom' => '',
			'badge'        => 'Tuition · PL & EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'headline'     => 'Pay in advance',
			'value'        => '−5% / −10%',
			'text'         => 'Semester in advance −5% · year in advance −10%',
			'meta'         => 'Deadline: 10 September',
			'link'         => '/kalkulator-czesnego/?promo=jednorazowo',
		],
		[
			'layout'       => 'media',
			'area'         => 'c',
			'color'        => 'lilac',
			'color_custom' => '',
			'badge'        => 'Tuition · Warsaw · Bachelor\'s',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-student-paint.jpg',
			'headline'     => 'Graduate of a<br><strong>technical/arts school</strong>',
			'value'        => '− PLN 1,200',
			'text'         => 'This year\'s secondary-school graduate · profile on the diploma',
			'meta'         => '',
			'link'         => '/kalkulator-czesnego/?promo=techart',
		],
		[
			'layout'       => 'media',
			'area'         => 'd',
			'color'        => 'sky',
			'color_custom' => '',
			'badge'        => 'Tuition · 1st & 2nd cycle',
			'badge_bg'     => '#c8dff2',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-students-grass.jpg',
			'headline'     => '<strong>Cheaper in a group</strong>',
			'value'        => '−PLN 400',
			'text'         => 'Discount applied proportionally across both semesters of the 2026/2027 academic year',
			'meta'         => 'Groups of 5+ · 2–4 people −PLN 200 · until 30 Sep',
			'link'         => '/kalkulator-czesnego/?promo=grupie&sub=400',
		],
		[
			'layout'       => 'solid',
			'area'         => 'e',
			'color'        => 'lime',
			'color_custom' => '',
			'badge'        => 'Tuition · PL & EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'headline'     => 'Enrolment fee waived <strong>PLN 0</strong>',
			'value'        => '',
			'text'         => 'instead of PLN 490 · when you enrol by 30 Oct 2026',
			'meta'         => '',
			'link'         => '/kalkulator-czesnego/?rekr=kurs',
		],
		[
			'layout'       => 'solid',
			'area'         => 'f',
			'color'        => 'apricot',
			'color_custom' => '',
			'badge'        => 'Tuition · PL & EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'headline'     => 'Transfer to ATA',
			'value'        => '−30%',
			'text'         => 'Transfer from another university · starting semester',
			'meta'         => '',
			'link'         => '/kalkulator-czesnego/?promo=przejscie',
		],
	],
];
