<?php

return [
	'show'  => true,
	'title' => 'Promocje',
	'cards' => [
		[
			'layout'       => 'media',
			'area'         => 'a',
			'color'        => 'peach',
			'color_custom' => '',
			'badge'        => 'Czesne · I stopień',
			'badge_bg'     => '#f5e06a',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-student-hoodie.jpg',
			'headline'     => 'Studia krok bliżej, <strong>1 000 zł taniej</strong>',
			'value'        => '',
			'text'         => 'Zniżka proporcjonalnie w obu semestrach roku akademickiego 2026/2027',
			'meta'         => 'Rejestracja do 30.08 · umowa do 30.09.2026',
			'link'         => '/kalkulator-czesnego/?promo=szybki',
		],
		[
			'layout'       => 'solid',
			'area'         => 'b',
			'color'        => 'pink',
			'color_custom' => '',
			'badge'        => 'Czesne · PL | EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'headline'     => 'Płatność z góry',
			'value'        => '−5% / −10%',
			'text'         => 'Semestr z góry −5% · rok z góry −10%',
			'meta'         => 'Termin: do 10 września',
			'link'         => '/kalkulator-czesnego/?promo=jednorazowo',
		],
		[
			'layout'       => 'media',
			'area'         => 'c',
			'color'        => 'lilac',
			'color_custom' => '',
			'badge'        => 'Czesne · Warszawa · I st.',
			'badge_bg'     => '#ddd0eb',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-student-paint.jpg',
			'headline'     => 'Absolwent szkoły<br><strong>techniczno/artystycznej</strong>',
			'value'        => '− 1 200 zł',
			'text'         => 'Tegoroczny maturzysta · profil na świadectwie',
			'meta'         => '',
			'link'         => '/kalkulator-czesnego/?promo=techart',
		],
		[
			'layout'       => 'media',
			'area'         => 'd',
			'color'        => 'sky',
			'color_custom' => '',
			'badge'        => 'Czesne · I i II stopień',
			'badge_bg'     => '#c8dff2',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-students-grass.jpg',
			'headline'     => '<strong>W Grupie Taniej</strong>',
			'value'        => '−400 zł',
			'text'         => 'Zniżka proporcjonalnie w obu semestrach roku akademickiego 2026/2027',
			'meta'         => 'Grupy 5+ osób · 2–4 osoby −200 zł · do 30.09',
			'link'         => '/kalkulator-czesnego/?promo=grupie&sub=400',
		],
		[
			'layout'       => 'solid',
			'area'         => 'e',
			'color'        => 'lime',
			'color_custom' => '',
			'badge'        => 'Czesne · PL | EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'headline'     => 'Wpisowe gratis <strong>0 zł</strong>',
			'value'        => '',
			'text'         => 'zamiast 490 zł · przy zapisie do 30.10.2026',
			'meta'         => '',
			'link'         => '/kalkulator-czesnego/?rekr=kurs',
		],
		[
			'layout'       => 'solid',
			'area'         => 'f',
			'color'        => 'apricot',
			'color_custom' => '',
			'badge'        => 'Czesne · PL | EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'headline'     => '<strong>Przejście do ATA</strong>',
			'value'        => '−30%',
			'text'         => 'Przeniesienie z innej uczelni · semestr startu',
			'meta'         => '',
			'link'         => '/kalkulator-czesnego/?promo=przejscie',
		],
	],
];
