<?php

/**
 * Russian defaults for homepage promotions section.
 *
 * @return array<string, mixed>
 */
return [
	'show'  => true,
	'title' => 'Акции',
	'cards' => [
		[
			'layout'       => 'media',
			'area'         => 'a',
			'color'        => 'peach',
			'color_custom' => '',
			'badge'        => 'Оплата за обучение · I ступень',
			'badge_bg'     => '#ffc862',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-student-hoodie.jpg',
			'headline'     => 'Обучение на шаг ближе, <strong>на 1 000 zł дешевле</strong>',
			'value'        => '',
			'text'         => 'Скидка пропорционально в обоих семестрах учебного года 2026/2027',
			'meta'         => 'Регистрация до 30.09 · договор до 30.10.2026',
			'link'         => '/kalkulator-czesnego/?promo=szybki',
		],
		[
			'layout'       => 'solid',
			'area'         => 'b',
			'color'        => 'pink',
			'color_custom' => '',
			'badge'        => 'Оплата за обучение · PL и EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'headline'     => 'Оплата вперёд',
			'value'        => '−5% / −10%',
			'text'         => 'Семестр вперёд −5% · год вперёд −10%',
			'meta'         => 'Срок: до 10 сентября',
			'link'         => '/kalkulator-czesnego/?promo=jednorazowo',
		],
		[
			'layout'       => 'media',
			'area'         => 'c',
			'color'        => 'lilac',
			'color_custom' => '',
			'badge'        => 'Оплата за обучение · Варшава · I ст.',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-student-paint.jpg',
			'headline'     => 'Выпускник школы<br><strong>технической/художественной</strong>',
			'value'        => '− 1 200 zł',
			'text'         => 'Выпускник этого года · профиль в аттестате',
			'meta'         => '',
			'link'         => '/kalkulator-czesnego/?promo=techart',
		],
		[
			'layout'       => 'media',
			'area'         => 'd',
			'color'        => 'sky',
			'color_custom' => '',
			'badge'        => 'Оплата за обучение · I и II ступень',
			'badge_bg'     => '#c8dff2',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-students-grass.jpg',
			'headline'     => '<strong>В группе дешевле</strong>',
			'value'        => '−400 zł',
			'text'         => 'Скидка пропорционально в обоих семестрах учебного года 2026/2027',
			'meta'         => 'Группы 5+ человек · 2–4 человека −200 zł · до 30.09',
			'link'         => '/kalkulator-czesnego/?promo=grupie&sub=400',
		],
		[
			'layout'       => 'solid',
			'area'         => 'e',
			'color'        => 'lime',
			'color_custom' => '',
			'badge'        => 'Оплата за обучение · PL и EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'headline'     => 'Вступительный взнос <strong>0 zł</strong>',
			'value'        => '',
			'text'         => 'вместо 490 zł · при записи до 30.10.2026',
			'meta'         => '',
			'link'         => '/kalkulator-czesnego/?rekr=kurs',
		],
		[
			'layout'       => 'solid',
			'area'         => 'f',
			'color'        => 'apricot',
			'color_custom' => '',
			'badge'        => 'Оплата за обучение · PL и EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'headline'     => 'Переход в ATA',
			'value'        => '−30%',
			'text'         => 'Перевод из другого вуза · семестр старта',
			'meta'         => '',
			'link'         => '/kalkulator-czesnego/?promo=przejscie',
		],
	],
];
