<?php

/**
 * Russian defaults for homepage promotions section.
 *
 * @return array<string, mixed>
 */
return [
	'show'  => true,
	'title' => 'Акции',
	'cards' => [
		[
			'layout'       => 'media',
			'area'         => 'a',
			'color'        => 'peach',
			'color_custom' => '',
			'badge'        => 'Оплата за обучение · I ступень',
			'badge_bg'     => '#ffc862',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-student-hoodie.jpg',
			'promo_id'     => 'szybki',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Скидка пропорционально в обоих семестрах учебного года 2026/2027',
			'meta'         => '',
			'link'         => '/oferta/?promo=szybki',
		],
		[
			'layout'       => 'solid',
			'area'         => 'b',
			'color'        => 'pink',
			'color_custom' => '',
			'badge'        => 'Оплата за обучение · PL и EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'promo_id'     => 'jednorazowo',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Семестр вперёд −5% · год вперёд −10%',
			'meta'         => '',
			'link'         => '/oferta/?promo=jednorazowo',
		],
		[
			'layout'       => 'media',
			'area'         => 'c',
			'color'        => 'lilac',
			'color_custom' => '',
			'badge'        => 'Оплата за обучение · Варшава · I ст.',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-student-paint.jpg',
			'promo_id'     => 'techart',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Выпускник этого года · профиль в аттестате',
			'meta'         => '',
			'link'         => '/oferta/?promo=techart',
		],
		[
			'layout'       => 'media',
			'area'         => 'd',
			'color'        => 'sky',
			'color_custom' => '',
			'badge'        => 'Оплата за обучение · I и II ступень',
			'badge_bg'     => '#c8dff2',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-students-grass.jpg',
			'promo_id'     => 'grupie',
			'sub'          => '400',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Скидка пропорционально в обоих семестрах учебного года 2026/2027',
			'meta'         => '',
			'link'         => '/oferta/?promo=grupie&sub=400',
		],
		[
			'layout'       => 'solid',
			'area'         => 'e',
			'color'        => 'lime',
			'color_custom' => '',
			'badge'        => 'Оплата за обучение · PL и EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'headline'     => 'Вступительный взнос <strong>0 zł</strong>',
			'value'        => '',
			'text'         => 'вместо 490 zł · при записи до 30.10.2026',
			'meta'         => '',
			'link'         => '/kalkulator-czesnego/?rekr=kurs',
		],
		[
			'layout'       => 'solid',
			'area'         => 'f',
			'color'        => 'apricot',
			'color_custom' => '',
			'badge'        => 'Оплата за обучение · PL и EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'promo_id'     => 'przejscie',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Перевод из другого вуза · семестр старта',
			'meta'         => '',
			'link'         => '/oferta/?promo=przejscie',
		],
	],
];
