<?php

/**
 * Ukrainian defaults for homepage promotions section.
 *
 * @return array<string, mixed>
 */
return [
	'show'  => true,
	'title' => 'Акції',
	'cards' => [
		[
			'layout'       => 'media',
			'area'         => 'a',
			'color'        => 'peach',
			'color_custom' => '',
			'badge'        => 'Внесок за навчання · I ступінь',
			'badge_bg'     => '#ffc862',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-student-hoodie.jpg',
			'promo_id'     => 'szybki',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Знижка пропорційно в обох семестрах навчального року 2026/2027',
			'meta'         => '',
			'link'         => '/oferta/?promo=szybki',
		],
		[
			'layout'       => 'solid',
			'area'         => 'b',
			'color'        => 'pink',
			'color_custom' => '',
			'badge'        => 'Внесок за навчання · PL і EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'promo_id'     => 'jednorazowo',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Семестр наперед −5% · рік наперед −10%',
			'meta'         => '',
			'link'         => '/oferta/?promo=jednorazowo',
		],
		[
			'layout'       => 'media',
			'area'         => 'c',
			'color'        => 'lilac',
			'color_custom' => '',
			'badge'        => 'Внесок за навчання · Варшава · I ст.',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-student-paint.jpg',
			'promo_id'     => 'techart',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Цьогорічний випускник · профіль у свідоцтві',
			'meta'         => '',
			'link'         => '/oferta/?promo=techart',
		],
		[
			'layout'       => 'media',
			'area'         => 'd',
			'color'        => 'sky',
			'color_custom' => '',
			'badge'        => 'Внесок за навчання · I і II ступінь',
			'badge_bg'     => '#c8dff2',
			'image'        => null,
			'image_url'    => 'static/img/home-promos/promo-students-grass.jpg',
			'promo_id'     => 'grupie',
			'sub'          => '400',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Знижка пропорційно в обох семестрах навчального року 2026/2027',
			'meta'         => '',
			'link'         => '/oferta/?promo=grupie&sub=400',
		],
		[
			'layout'       => 'solid',
			'area'         => 'e',
			'color'        => 'lime',
			'color_custom' => '',
			'badge'        => 'Внесок за навчання · PL і EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'headline'     => 'Вступний внесок <strong>0 zł</strong>',
			'value'        => '',
			'text'         => 'замість 490 zł · при записі до 30.10.2026',
			'meta'         => '',
			'link'         => '/oferta/',
		],
		[
			'layout'       => 'solid',
			'area'         => 'f',
			'color'        => 'apricot',
			'color_custom' => '',
			'badge'        => 'Внесок за навчання · PL і EN',
			'badge_bg'     => '',
			'image'        => null,
			'image_url'    => '',
			'promo_id'     => 'przejscie',
			'headline'     => '',
			'value'        => '',
			'text'         => 'Переведення з іншого ВНЗ · семестр старту',
			'meta'         => '',
			'link'         => '/oferta/?promo=przejscie',
		],
	],
];
