<?php

/**
 * @return array<string, array<string, mixed>>
 */
return [
    'kato_hero_section' => [
        'watermark' => 'katalog',
        'eyebrow' => 'Kreowanie przestrzeni / katalog kierunków',
        'title' => 'Wybierz kierunek związany z projektowaniem przestrzeni.',
        'lead' => 'Architektura, architektura wnętrz, architektura krajobrazu, budownictwo i ochrona środowiska w jednym miejscu. Skorzystaj z filtrów, porównaj miasta, sprawdź czas trwania studiów i przejdź od razu do szczegółów lub zapisu.',
        'cta_primary_text' => 'Sprawdź szczegóły',
        'cta_primary_url' => '#katalog',
        'cta_secondary_text' => 'Zapisz się',
        'cta_secondary_url' => '#katalog',
        'panel_title' => 'Znajdź kierunek związany z projektowaniem przestrzeni, który jest odpowiedni dla Ciebie',
        'stats' => [
            ['number' => '12', 'text' => 'kierunków i ścieżek do sprawdzenia'],
            ['number' => '2', 'text' => 'miasta: Warszawa i Wrocław'],
            ['number' => '5', 'text' => 'grup tematycznych do filtrowania'],
            ['number' => '2', 'text' => 'proste kroki: sprawdź szczegóły lub zapisz się'],
        ],
    ],
    'kato_catalog_section' => [
        'watermark' => 'kierunki',
        'eyebrow' => 'Katalog kierunków',
        'title' => 'Sprawdź kierunki i wybierz swoją ścieżkę.',
        'intro' => 'Nie musisz przeglądać całej oferty uczelni. Wybierz miasto i obszar, który Cię interesuje, a potem przejdź od razu do szczegółów kierunku albo zapisu.',
        'filter_title' => 'Filtruj kierunki',
        'filter_text' => 'Wybierz miasto i obszar, aby zawęzić listę kierunków związanych z kreowaniem przestrzeni.',
        'result_count_suffix' => 'kierunków do sprawdzenia',
        'city_filters' => [
            ['slug' => 'all', 'label' => 'Wszystkie miasta'],
            ['slug' => 'warszawa', 'label' => 'Warszawa'],
            ['slug' => 'wroclaw', 'label' => 'Wrocław'],
        ],
        'area_filters' => [
            ['slug' => 'all', 'label' => 'Wszystkie obszary'],
            ['slug' => 'architektura', 'label' => 'Architektura'],
            ['slug' => 'wnetrza', 'label' => 'Wnętrza'],
            ['slug' => 'krajobraz', 'label' => 'Krajobraz'],
            ['slug' => 'budownictwo', 'label' => 'Budownictwo'],
            ['slug' => 'srodowisko', 'label' => 'Środowisko'],
        ],
        'no_results_title' => 'Brak wyników dla wybranych filtrów',
        'no_results_text' => 'Zmień miasto albo obszar, aby zobaczyć inne kierunki związane z kreowaniem przestrzeni.',
        'courses' => [
            [
                'city' => 'warszawa',
                'area' => 'architektura',
                'visual_variant' => 'arch',
                'visual_svg' => 'arch_1',
                'location' => 'Warszawa',
                'course_type' => 'Architektura',
                'title' => 'Architektura',
                'text' => 'Projektowanie budynków, miasta i przestrzeni publicznych. Kierunek dla osób, które chcą łączyć kreatywność, technikę i odpowiedzialność projektową.',
                'meta' => [
                    ['label' => 'inżynier architekt'],
                    ['label' => '4 lata'],
                    ['label' => 'PL / EN'],
                    ['label' => 'Warszawa'],
                ],
                'details_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/architektura/',
                'register_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/architektura/',
            ],
            [
                'city' => 'wroclaw',
                'area' => 'architektura',
                'visual_variant' => 'arch',
                'visual_svg' => 'arch_2',
                'location' => 'Wrocław',
                'course_type' => 'Architektura',
                'title' => 'Architektura Wrocław',
                'text' => 'Studia architektoniczne w mieście pełnym różnorodnej architektury, nowych inwestycji i inspirujących przestrzeni.',
                'meta' => [
                    ['label' => 'inżynier architekt'],
                    ['label' => '4 lata'],
                    ['label' => 'język polski'],
                    ['label' => 'Wrocław'],
                ],
                'details_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/architektura-wroclaw/',
                'register_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/architektura-wroclaw/',
            ],
            [
                'city' => 'warszawa',
                'area' => 'wnetrza',
                'visual_variant' => 'interior',
                'visual_svg' => 'interior_1',
                'location' => 'Warszawa',
                'course_type' => 'Wnętrza',
                'title' => 'Architektura wnętrz',
                'text' => 'Projektowanie mieszkań, biur, hoteli, lokali usługowych, wystaw i przestrzeni, które mają działać funkcjonalnie i dobrze wyglądać.',
                'meta' => [
                    ['label' => 'licencjat'],
                    ['label' => '3,5 roku'],
                    ['label' => 'język polski'],
                    ['label' => 'Warszawa'],
                ],
                'details_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/architektura-wnetrz/',
                'register_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/architektura-wnetrz/',
            ],
            [
                'city' => 'wroclaw',
                'area' => 'wnetrza',
                'visual_variant' => 'interior',
                'visual_svg' => 'interior_2',
                'location' => 'Wrocław',
                'course_type' => 'Wnętrza',
                'title' => 'Architektura wnętrz Wrocław',
                'text' => 'Studia I stopnia dostępne również we Wrocławiu. To ścieżka dla osób, które chcą projektować wnętrza, funkcję i atmosferę przestrzeni.',
                'meta' => [
                    ['label' => 'licencjat'],
                    ['label' => '3,5 roku'],
                    ['label' => 'język polski'],
                    ['label' => 'Wrocław'],
                ],
                'details_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/wroclaw-architektura-wnetrz/',
                'register_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/wroclaw-architektura-wnetrz/',
            ],
            [
                'city' => 'warszawa',
                'area' => 'krajobraz',
                'visual_variant' => 'landscape',
                'visual_svg' => 'landscape_1',
                'location' => 'Warszawa',
                'course_type' => 'Krajobraz',
                'title' => 'Architektura krajobrazu',
                'text' => 'Projektowanie ogrodów, parków, terenów rekreacyjnych, zieleni i przestrzeni zewnętrznych przyjaznych ludziom oraz środowisku.',
                'meta' => [
                    ['label' => 'inżynier'],
                    ['label' => '3,5 roku'],
                    ['label' => 'język polski'],
                    ['label' => 'Warszawa'],
                ],
                'details_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/architektura-krajobrazu/',
                'register_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/architektura-krajobrazu/',
            ],
            [
                'city' => 'warszawa',
                'area' => 'krajobraz',
                'visual_variant' => 'landscape',
                'visual_svg' => 'landscape_2',
                'location' => 'Warszawa',
                'course_type' => 'Krajobraz',
                'title' => 'Projektowanie krajobrazu o funkcji rekreacyjnej',
                'text' => 'Ścieżka dla osób, które chcą projektować przestrzenie wypoczynku, sportu, aktywności i rekreacji w powiązaniu z ochroną środowiska.',
                'meta' => [
                    ['label' => 'specjalność'],
                    ['label' => 'rekreacja'],
                    ['label' => 'środowisko'],
                    ['label' => 'Warszawa'],
                ],
                'details_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/projektowanie-krajobrazu-o-funkcji-rekreacyjnej/',
                'register_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/projektowanie-krajobrazu-o-funkcji-rekreacyjnej/',
            ],
            [
                'city' => 'warszawa',
                'area' => 'krajobraz',
                'visual_variant' => 'landscape',
                'visual_svg' => 'landscape_3',
                'location' => 'Warszawa',
                'course_type' => 'Krajobraz',
                'title' => 'Projektowanie krajobrazu wielofunkcyjnego',
                'text' => 'Kierunek dla osób, które chcą łączyć estetykę, funkcję, ekologię i planowanie przestrzeni dla różnych użytkowników.',
                'meta' => [
                    ['label' => 'specjalność'],
                    ['label' => 'ekologia'],
                    ['label' => 'funkcja'],
                    ['label' => 'Warszawa'],
                ],
                'details_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/projektowanie-krajobrazu-wielofunkcyjnego/',
                'register_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/projektowanie-krajobrazu-wielofunkcyjnego/',
            ],
            [
                'city' => 'warszawa',
                'area' => 'budownictwo',
                'visual_variant' => 'build',
                'visual_svg' => 'build_1',
                'location' => 'Warszawa',
                'course_type' => 'Budownictwo',
                'title' => 'Budownictwo',
                'text' => 'Techniczna ścieżka dla osób zainteresowanych procesem budowlanym, inwestycjami, realizacją obiektów i nowoczesnym budownictwem.',
                'meta' => [
                    ['label' => 'inżynier'],
                    ['label' => '3,5 roku'],
                    ['label' => 'PL / EN'],
                    ['label' => 'Warszawa'],
                ],
                'details_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/budownictwo/',
                'register_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/budownictwo/',
            ],
            [
                'city' => 'warszawa',
                'area' => 'budownictwo',
                'visual_variant' => 'build',
                'visual_svg' => 'build_2',
                'location' => 'Warszawa',
                'course_type' => 'Budownictwo',
                'title' => 'Konstrukcje budowlane',
                'text' => 'Ścieżka dla osób, które chcą rozwijać kompetencje techniczne związane z projektowaniem, analizą i realizacją konstrukcji.',
                'meta' => [
                    ['label' => 'inżynier'],
                    ['label' => 'konstrukcje'],
                    ['label' => 'Warszawa'],
                ],
                'details_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/konstrukcje-budowlane/',
                'register_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/konstrukcje-budowlane/',
            ],
            [
                'city' => 'warszawa',
                'area' => 'budownictwo',
                'visual_variant' => 'build',
                'visual_svg' => 'build_3',
                'location' => 'Warszawa',
                'course_type' => 'Budownictwo',
                'title' => 'Energooszczędne technologie w budownictwie',
                'text' => 'Kierunek dla osób, które chcą łączyć budownictwo z efektywnością energetyczną i nowoczesnymi rozwiązaniami dla obiektów.',
                'meta' => [
                    ['label' => 'inżynier'],
                    ['label' => '3,5 roku'],
                    ['label' => 'energooszczędność'],
                    ['label' => 'Warszawa'],
                ],
                'details_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/energooszczedne-technologie-w-budownictwie/',
                'register_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/energooszczedne-technologie-w-budownictwie/',
            ],
            [
                'city' => 'warszawa',
                'area' => 'srodowisko',
                'visual_variant' => 'env',
                'visual_svg' => 'env_1',
                'location' => 'Warszawa',
                'course_type' => 'Środowisko',
                'title' => 'Ochrona środowiska',
                'text' => 'Kierunek dla osób, które chcą myśleć o przestrzeni w odpowiedzialny sposób: środowisko, zasoby, zieleń, gospodarka wodna i zrównoważony rozwój.',
                'meta' => [
                    ['label' => 'inżynier'],
                    ['label' => '3,5 roku'],
                    ['label' => 'środowisko'],
                    ['label' => 'Warszawa'],
                ],
                'details_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/ochrona-srodowiska/',
                'register_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/ochrona-srodowiska/',
            ],
            [
                'city' => 'warszawa',
                'area' => 'srodowisko',
                'visual_variant' => 'env',
                'visual_svg' => 'env_2',
                'location' => 'Warszawa',
                'course_type' => 'Środowisko',
                'title' => 'Odnawialne źródła energii, gospodarka wodna i odpadowa',
                'text' => 'Ścieżka dla osób, które chcą łączyć ochronę środowiska z energią, wodą, odpadami i praktycznymi rozwiązaniami dla miast.',
                'meta' => [
                    ['label' => 'inżynier'],
                    ['label' => 'OZE'],
                    ['label' => 'woda'],
                    ['label' => 'odpady'],
                ],
                'details_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/odnawialne-zrodla-energii-gospodarka-wodna-i-odpadowa/',
                'register_url' => 'https://akademiata.pl/oferta/studia-1-stopnia/odnawialne-zrodla-energii-gospodarka-wodna-i-odpadowa/',
            ],
        ],
    ],
    'kato_final_section' => [
        'title' => 'Wybierz kierunek i przejdź od razu do szczegółów albo zapisu.',
        'text' => 'Katalog kierunków pomaga szybko znaleźć studia związane z architekturą, wnętrzami, krajobrazem, budownictwem i środowiskiem. To ostatni krok przed wejściem w pełny opis kierunku.',
        'cta_primary_text' => 'Sprawdź szczegóły',
        'cta_primary_url' => '#katalog',
        'cta_secondary_text' => 'Zapisz się',
        'cta_secondary_url' => '#katalog',
    ],
];
