<?php

/**
 * @return array<string, array<string, mixed>>
 */
return [
    'rekr_hero_section' => [
        'watermark' => 'Rekrutacja',
        'eyebrow' => 'Rekrutacja na ATA',
        'title' => 'Rekrutacja na ATA - wszystkie informacje w jednym miejscu.',
        'lead' => 'Wszystko, czego potrzebujesz, żeby zacząć studia w ATA — zasady przyjęć, terminy, dokumenty i opłaty dla kandydatów z Polski i z zagranicy. Wybierz swoją ścieżkę i przejdź przez proces krok po kroku, w dużej części online.',
        'cta_primary_text' => 'Wybierz swoją ofertę',
        'cta_primary_url' => 'https://akademiata.pl/oferta/',
        'cta_secondary_text' => 'Sprawdź terminy',
        'cta_secondary_url' => '#terminy',
        'hero_reassure' => 'Na większości kierunków decyduje kolejność zgłoszeń — bez egzaminów wstępnych. Rekrutację w dużej części przejdziesz online.',
        'hero_photo' => null,
        'hero_tag' => 'Rekrutacja 2026/2027',
        'hero_bar' => [
            ['value' => '1 kwietnia', 'label' => 'start rekrutacji'],
            ['value' => '2 miasta', 'label' => 'Warszawa i Wrocław'],
            ['value' => 'online', 'label' => 'w dużej części zdalnie'],
        ],
    ],
    'rekr_trust_section' => [
        'items' => [
            [
                'number' => '#1',
                'text' => 'w Warszawie i we Wrocławiu',
                'note' => 'niepubliczne uczelnie zawodowe · Perspektywy 2026',
            ],
            [
                'number' => '4',
                'text' => 'kierunki nr 1 w Polsce',
                'note' => 'dane ZUS · ELA',
            ],
            [
                'number' => '0',
                'text' => 'egzaminów na większości kierunków',
                'note' => 'decyduje kolejność zgłoszeń',
            ],
            [
                'number' => '2',
                'text' => 'miasta — Warszawa i Wrocław',
                'note' => 'studia I i II stopnia',
            ],
        ],
    ],
    'rekr_quick_nav' => [
        'label_title' => 'Szukasz konkretnej informacji?',
        'label_text' => 'Kliknij temat i przejdź prosto do niego.',
        'links' => [
            ['text' => 'Wybierz ścieżkę', 'anchor' => '#sciezka'],
            ['text' => 'Kierunki i portfolio', 'anchor' => '#kierunki'],
            ['text' => 'Terminy', 'anchor' => '#terminy'],
            ['text' => 'Kandydaci z Polski', 'anchor' => '#polska'],
            ['text' => 'Dokumenty (PL)', 'anchor' => '#dokumenty-pl'],
            ['text' => 'Kandydaci zagraniczni', 'anchor' => '#zagraniczni'],
            ['text' => 'Dokumenty (ENG)', 'anchor' => '#foreign-docs'],
            ['text' => 'Wiza i pobyt', 'anchor' => '#pobyt'],
            ['text' => 'Przeniesienie', 'anchor' => '#przeniesienie'],
            ['text' => 'Pliki do pobrania', 'anchor' => '#pliki'],
            ['text' => 'Kontakt', 'anchor' => '#kontakt'],
            ['text' => 'FAQ', 'anchor' => '#faq'],
        ],
    ],
    'rekr_route_section' => [
        'watermark' => 'Wybierz',
        'eyebrow' => 'Wybierz swoją ścieżkę',
        'title' => 'Najpierw sprawdź, które informacje dotyczą Ciebie.',
        'intro' => 'Proces różni się w zależności od obywatelstwa, poziomu studiów oraz kierunku. Zacznij od odpowiedniej ścieżki, a następnie sprawdź terminy i dokumenty.',
        'cards' => [
            [
                'title' => 'Kandydaci z Polski',
                'text' => 'Zarejestruj się online, sprawdź wymagania wybranego kierunku, umów wizytę, wnieś opłaty i złóż dokumenty.',
                'items' => [
                    'rejestracja online i wydruk kwestionariusza',
                    'osobista wizyta w Warszawie lub we Wrocławiu',
                    'złożenie dokumentów i podpisanie umowy',
                ],
                'cta_text' => 'Przejdź do swojej ścieżki',
                'cta_url' => '#polska',
                'is_dark' => false,
            ],
            [
                'title' => 'Kandydaci zagraniczni',
                'text' => 'Aplikuj na studia w języku polskim lub angielskim. Sprawdź dokumenty zagraniczne, opłaty, zaproszenie, wizę, legalizację pobytu i wymagania językowe.',
                'items' => [
                    'rejestracja i skany dokumentów online',
                    'tłumaczenia, apostille, język B2 i uznanie świadectwa',
                    'formalności przed przyjazdem i po przyjeździe do Polski',
                ],
                'cta_text' => 'Przejdź do swojej ścieżki',
                'cta_url' => '#zagraniczni',
                'is_dark' => true,
            ],
        ],
    ],
    'rekr_paths_section' => [
        'watermark' => 'Kierunki',
        'eyebrow' => 'Wymagania zależne od kierunku',
        'title' => 'Sprawdź, jak wygląda rekrutacja na Twój kierunek.',
        'intro' => 'Na większości kierunków o przyjęciu decyduje kolejność zgłoszeń. Dodatkowe wymagania dotyczą kierunków projektowych.',
        'cards' => [
            [
                'tag' => 'Portfolio',
                'title' => 'Architektura - studia I stopnia',
                'text' => 'Jeśli wybierasz Architekturę, dołącz portfolio prac plastycznych. Portfolio złożysz w dowolnym momencie — oceniamy je w wyznaczonych turach (kwiecień–wrzesień).',
                'cta_text' => 'Sprawdź wymagania portfolio',
                'cta_url' => '#portfolio-wymagania',
                'cta_style' => 'default',
            ],
            [
                'tag' => 'Sprawdzian',
                'title' => 'Architektura Wnętrz i Wzornictwo - studia I stopnia',
                'text' => 'Podstawą przyjęcia jest pozytywny wynik sprawdzianu uzdolnień plastycznych. Terminy są ustalane osobno dla Warszawy i Wrocławia.',
                'cta_text' => 'Sprawdź terminy sprawdzianów',
                'cta_url' => '#terminy',
                'cta_style' => 'default',
            ],
            [
                'tag' => 'Rozmowa i portfolio',
                'title' => 'Architektura Wnętrz - studia II stopnia',
                'text' => 'Przygotuj portfolio, które zaprezentujesz podczas rozmowy kwalifikacyjnej. Sprawdź datę rozmowy i termin rejestracji.',
                'cta_text' => 'Sprawdź terminy rozmów',
                'cta_url' => '#terminy',
                'cta_style' => 'default',
            ],
            [
                'tag' => 'Kolejność zgłoszeń',
                'title' => 'Pozostałe kierunki',
                'text' => 'Na większość kierunków studiów I i II stopnia nie ma egzaminów wstępnych. Nie musisz zdawać określonych przedmiotów na maturze.',
                'cta_text' => 'Rozpocznij rekrutację',
                'cta_url' => 'https://akademiata.pl/oferta/',
                'cta_style' => 'blue',
            ],
        ],
    ],
    'rekr_portfolio_section' => [
        'col1_eyebrow' => 'Portfolio - Architektura I stopnia',
        'col1_title' => 'Co powinno zawierać portfolio?',
        'col1_text' => 'Portfolio powinno składać się z od 5 do 10 prac wykonanych ołówkiem, w formacie co najmniej A3.',
        'checklist' => [
            'co najmniej 3 rysunki przedstawiające architekturę',
            'co najmniej 2 rysunki przedstawiające kompozycje z prostych brył geometrycznych, elementów wyposażenia i tkanin',
            'wyłącznie własne prace kandydata',
            'czytelne fotografie lub skany prac, jeśli portfolio przesyłasz online',
        ],
        'col2_eyebrow' => 'Jak przekazać prace?',
        'col2_title' => 'Prześlij je online albo złóż w uczelni.',
        'col2_text' => 'Portfolio możesz złożyć w dowolnym momencie — online na swoim koncie w systemie rekrutacyjnym albo osobiście, przynosząc teczkę z oryginalnymi pracami do Działu Rekrutacji. Oceniamy je w kolejnych, wyznaczonych turach — sprawdź, kiedy wypada najbliższa.',
        'gallery_toggle_text' => 'Zobacz przykładowe portfolio',
        'gallery_toggle_url' => 'https://uczelnia.akademiata.pl/przyklady-prawidlowo-wykonanego-portfolio/',
        'gallery_link_text' => 'Sprawdź terminy oceny',
        'gallery_bar' => '<strong>Przykładowe prace z wcześniejszych naborów</strong> — bryły geometryczne, martwa natura i architektura. To poziom i charakter prac, jakiego oczekujemy. Kliknij dowolną pracę, aby ją powiększyć.',
        'gallery_images' => null,
    ],
    'rekr_terms_section' => [
        'watermark' => 'Terminy',
        'eyebrow' => 'Harmonogram 2026/2027',
        'title' => 'Sprawdź terminy portfolio, sprawdzianów i rozmów kwalifikacyjnych.',
        'intro' => 'Przy sprawdzianach i rozmowach pamiętaj także o terminie rejestracji w systemie rekrutacyjnym.',
        'term_cards' => [
            [
                'label' => '1 kwietnia',
                'title' => 'Start rekrutacji',
                'text' => 'Rekrutacja na semestr zimowy 2026/2027 rozpoczyna się 1 kwietnia 2026 roku.',
                'is_dark' => false,
            ],
            [
                'label' => 'Harmonogramy',
                'title' => 'Terminy składania portfolio, sprawdzianów, rekrutacji i rozmów kwalifikacyjnych',
                'text' => 'Trwają od kwietnia do września 2026 roku.',
                'is_dark' => false,
            ],
            [
                'label' => '2 miasta',
                'title' => 'Warszawa i Wrocław',
                'text' => 'Sprawdziany uzdolnień plastycznych odbywają się w kilku terminach w obu miastach.',
                'is_dark' => true,
            ],
        ],
        'schedule_toggle_label' => 'Pełny harmonogram 2026',
        'schedule_blocks' => [
            [
                'title' => 'Portfolio - Architektura I stopnia',
                'items' => [
                    'I: 1-17 kwietnia',
                    'II: 20-30 kwietnia',
                    'III: 4-15 maja',
                    'IV: 19-30 maja',
                    'V: 3-19 czerwca',
                    'VI: 22 czerwca - 15 lipca',
                    'VII: 17-30 lipca',
                    'VIII: 7-22 sierpnia',
                    'IX: 25 sierpnia - 5 września',
                    'X: 8-14 września',
                    'XI: 17-25 września',
                ],
            ],
            [
                'title' => 'Sprawdzian - Warszawa',
                'items' => [
                    '25 maja - rejestracja do 21 maja',
                    '8 czerwca - do 4 czerwca',
                    '14 lipca - do 11 lipca',
                    '28 lipca - do 24 lipca',
                    '10 sierpnia - do 7 sierpnia',
                    '7 września - do 4 września',
                    '15 września - do 13 września',
                    '25 września - do 23 września',
                ],
            ],
            [
                'title' => 'Sprawdzian - Wrocław',
                'items' => [
                    '28 maja - rejestracja do 24 maja',
                    '23 czerwca - do 19 czerwca',
                    '10 lipca - do 6 lipca',
                    '24 lipca - do 20 lipca',
                    '14 sierpnia - do 10 sierpnia',
                    '14 września - do 10 września',
                    '28 września - do 24 września',
                ],
            ],
            [
                'title' => 'Rozmowa - Architektura Wnętrz II stopnia',
                'items' => [
                    '15 czerwca - rejestracja do 11 czerwca',
                    '16 lipca - do 12 lipca',
                    '13 sierpnia - do 9 sierpnia',
                    '11 września - do 8 września',
                    '28 września - do 24 września',
                ],
            ],
        ],
        'warning_html' => '<strong>Pozostałe kierunki:</strong> Zarządzanie, Zarządzanie i Inżynieria Produkcji, Ochrona Środowiska, Mechanika i Budowa Maszyn, Architektura Krajobrazu, Informatyka, Budownictwo, Finanse i Rachunkowość, Logistyka, Komunikacja Cyfrowa i Media oraz Turystyka i Rekreacja - zapisy trwają do wyczerpania miejsc.',
    ],
    'rekr_poland_section' => [
        'watermark' => 'Polska',
        'eyebrow' => 'Rekrutacja - krok po kroku',
        'title' => 'Kandydaci z Polski',
        'intro' => 'Przejdź przez sześć etapów. Dokumenty złożysz i podpiszesz umowę podczas jednej, wcześniej umówionej wizyty.',
        'steps' => [
            [
                'number' => '1',
                'title' => 'Rejestracja online',
                'text' => 'Załóż konto, wybierz kierunek i wypełnij kwestionariusz ATA.',
                'micro' => 'Sprawdź dane, uzupełnij numer i datę świadectwa lub dyplomu, a następnie wydrukuj kwestionariusz.',
            ],
            [
                'number' => '2',
                'title' => 'Umówienie wizyty',
                'text' => 'Zadzwoń do Działu Rekrutacji w Warszawie lub we Wrocławiu i wybierz dogodny termin osobistego złożenia dokumentów.',
                'micro' => 'Kandydaci umówieni na konkretną godzinę są obsługiwani w pierwszej kolejności.',
            ],
            [
                'number' => '3',
                'title' => 'Opłaty',
                'text' => 'Wnieś opłaty na konto wskazane w rekrutacji online przed wizytą i podpisaniem umowy.',
                'micro' => 'Przy przelewie tradycyjnym wpisz imię i nazwisko, adres oraz nazwę kierunku.',
            ],
            [
                'number' => '4',
                'title' => 'Złóż dokumenty',
                'text' => 'Przynieś komplet dokumentów do Działu Rekrutacji. Oryginały służą do wglądu i weryfikacji danych.',
                'micro' => 'Potwierdzenie opłaty możesz pokazać na telefonie lub przesłać e-mailem.',
            ],
            [
                'number' => '5',
                'title' => 'Podpisanie umowy',
                'text' => 'Podpisz umowę dotyczącą warunków płatności za studia podczas tej samej wizyty.',
                'micro' => 'Jeśli jesteś niepełnoletni, przyjdź z opiekunem prawnym.',
            ],
            [
                'number' => '6',
                'title' => 'Witaj na naszej uczelni!',
                'text' => 'Po zakończeniu formalności zostaniesz wpisany na listę studentów.',
                'micro' => 'Jeśli zabraknie miejsca po dokonaniu wpłaty, uczelnia zwróci opłaty wniesione przed zapisem.',
            ],
        ],
        'note_html' => '<strong>Nie masz jeszcze świadectwa dojrzałości?</strong> Na kierunkach bez portfolio i sprawdzianu możesz wcześniej zarejestrować się i dokonać opłaty rekrutacyjnej, aby zarezerwować miejsce. Ostateczne przyjęcie następuje po dostarczeniu kompletnego świadectwa dojrzałości i pozostałych dokumentów.',
        'reassure_tag' => 'Zdarza się rzadko',
        'reassure_title' => 'A jeśli kierunek nie ruszy?',
        'reassure_text' => 'To rzadka sytuacja. Gdyby jednak zaszła, uczelnia zwróci wpłacone środki — wystarczy kontakt z Działem Rekrutacji. Możesz też wybrać inny, pokrewny kierunek; pomożemy Ci dobrać najlepszy.',
        'reassure_photo' => null,
        'transfer_title' => 'Studiujesz już na innej uczelni?',
        'transfer_text' => 'Jeśli ukończyłeś studia na innym kierunku, chcesz zmienić kierunek, wznowić naukę po latach albo rozpocząć drugi kierunek, możesz ubiegać się o przyjęcie z różnicami programowymi i kontynuować studia na wyższym semestrze.',
        'transfer_items' => [
            'prześlij podanie do Dziekana z dopiskiem „Różnice programowe” na adres rekrutacja@akademiata.pl',
            'dołącz dokument potwierdzający przebieg studiów z liczbą godzin, punktami ECTS i ocenami',
            'przygotuj czytelne dokumenty w jednym pliku; oryginały okażesz podczas zapisu na studia',
            'decyzja jest podejmowana na podstawie zbieżności efektów uczenia się i zaliczonych przedmiotów',
        ],
        'transfer_note_html' => '<strong>Co zyskujesz?</strong> Nie płacisz za rozpatrzenie podania, płacisz jedynie za ewentualne różnice programowe oraz bieżące czesne. Nie musisz też powtarzać przedmiotów zgodnych z programem studiów w ATA, więc oszczędzasz czas.',
        'transfer_cta_text' => 'Pobierz podanie do Dziekana',
        'transfer_cta_url' => 'https://chmurka.wseiz.pl/index.php/s/RYatRf3iedzXgoX',
    ],
    'rekr_docs_pl_section' => [
        'watermark' => 'Dokumenty',
        'eyebrow' => 'Przygotuj listę odpowiednią do poziomu studiów',
        'title' => 'Wymagane dokumenty - kandydaci z Polski',
        'intro' => 'Wybierz zakładkę i sprawdź, co należy dostarczyć podczas wizyty.',
        'tabs' => [
            [
                'label' => 'Studia I stopnia',
                'items' => [
                    'wypełniony i wygenerowany z rekrutacji online kwestionariusz uczelniany',
                    'oryginał i kserokopia świadectwa dojrzałości - oryginał do wglądu',
                    'dowód osobisty do wglądu',
                    'jedno aktualne, podpisane zdjęcie 3,5 x 4,5 cm, wykonane frontem na białym tle',
                    'zaświadczenie lekarskie wyłącznie dla Ochrony Środowiska I i II stopnia',
                    'potwierdzenie wniesienia opłat związanych z rekrutacją',
                ],
                'note_html' => null,
                'warning_html' => '<strong>Ważne:</strong> odpis świadectwa nie jest kserokopią. Świadectwo ukończenia szkoły średniej nie zastępuje świadectwa dojrzałości.',
            ],
            [
                'label' => 'Studia II stopnia',
                'items' => [
                    'oryginał i kserokopia dyplomu ukończenia studiów wyższych',
                    'oryginał i kserokopia suplementu do dyplomu',
                    'kwestionariusz wygenerowany z rekrutacji online',
                    'dowód osobisty do wglądu',
                    'zdjęcie 3,5 x 4,5 cm',
                    'potwierdzenie wniesienia opłat',
                ],
                'note_html' => 'Na studia II stopnia nie musisz dostarczać świadectwa dojrzałości ani świadectwa ukończenia szkoły średniej. Te zasady dotyczą także absolwentów ATA.',
                'warning_html' => null,
            ],
            [
                'label' => 'Zdjęcie i opłaty',
                'items' => [
                    'zdjęcie powinno być aktualne, podpisane, wykonane frontem i na białym tle',
                    'zdjęcie wgrane do systemu powinno być takie samo jak wersja papierowa',
                    'potwierdzenia opłat nie musisz drukować - możesz pokazać je na telefonie lub przesłać e-mailem',
                    'skierowanie na badania dla Ochrony Środowiska otrzymasz podczas zapisu',
                    'badanie może być wykonane bezpłatnie w ramach dostępnych limitów placówek',
                ],
                'note_html' => null,
                'warning_html' => null,
            ],
        ],
    ],
    'rekr_foreign_section' => [
        'watermark' => 'International',
        'eyebrow' => 'Kandydaci zagraniczni',
        'title' => 'Rekrutacja kandydatów zagranicznych - od zgłoszenia do przyjazdu.',
        'intro' => 'Możesz aplikować na studia w języku polskim albo angielskim. Sprawdź wymagania dokumentowe, opłaty, wizę, legalizację pobytu i informacje po przyjeździe.',
        'app_title' => 'Rozpocznij rekrutację online',
        'app_text' => 'System Smart Apply jest dostępny w języku polskim, angielskim, rosyjskim i ukraińskim. Po przejściu do systemu wybierz język interfejsu, kierunek oraz język studiów. Na studia prowadzone po polsku lub angielsku przygotuj dokument potwierdzający znajomość właściwego języka na poziomie B2.',
        'app_cta_text' => 'Wybierz kierunek',
        'app_cta_url' => 'https://akademiata.pl/oferta/',
        'steps' => [
            [
                'number' => '1',
                'title' => 'Rejestracja online',
                'text' => 'Załóż konto i wpisz dane alfabetem łacińskim, zgodnie z paszportem, dowodem osobistym albo oficjalnym tłumaczeniem.',
                'micro' => 'Rejestracja zajmuje około 10 minut. Brakujące dane możesz uzupełnić później.',
            ],
            [
                'number' => '2',
                'title' => 'Prześlij skany',
                'text' => 'Dodaj dokument tożsamości, fotografię, świadectwo albo dyplom z suplementem, apostille i wymagane tłumaczenia.',
                'micro' => 'Pierwsza strona paszportu służy do weryfikacji danych i nie jest przechowywana w aktach.',
            ],
            [
                'number' => '3',
                'title' => 'Sprawdź dodatkowy egzamin',
                'text' => 'Kandydaci na studia I stopnia z dokumentami wydanymi poza UE, EFTA, OECD, Ukrainą i Chinami przystępują do internetowego egzaminu wstępnego ATA.',
                'micro' => 'Na Architekturę obowiązuje też portfolio, a na Architekturę Wnętrz i Wzornictwo - egzamin z rysunku.',
            ],
            [
                'number' => '4',
                'title' => 'Dokonaj opłaty',
                'text' => 'Pobierz fakturę z konta użytkownika. Faktura jest generowana w złotych i obejmuje co najmniej dwie raty czesnego, opłatę rekrutacyjną, wpisową i zaproszenie.',
                'micro' => 'Możesz zapłacić w euro. Potwierdzenie prześlij na swoje konto.',
            ],
            [
                'number' => '5',
                'title' => 'Odbierz zaproszenie',
                'text' => 'Po opłaceniu faktury otrzymasz zaproszenie potrzebne do wizy w wersji elektronicznej i pocztą.',
                'micro' => 'Jeśli nie potrzebujesz wizy, możesz pominąć ten etap. Kuriera zamawiasz na własny koszt.',
            ],
            [
                'number' => '6',
                'title' => 'Aplikuj o wizę',
                'text' => 'Sprawdź wymagania konsulatu, przygotuj oryginały dokumentów i poinformuj Biuro Współpracy Międzynarodowej o decyzji wizowej.',
                'micro' => 'W razie odmowy otrzymasz informacje o procedurze zwrotu opłat.',
            ],
            [
                'number' => '7',
                'title' => 'Przyjedź do Polski',
                'text' => 'Poinformuj Biuro Współpracy Międzynarodowej o terminie przyjazdu i ustal termin podpisania umowy.',
                'micro' => 'W ciągu 2 dni roboczych od przyjazdu dostarcz oryginały i kopie dokumentów.',
            ],
            [
                'number' => '8',
                'title' => 'Zarezerwuj akademik',
                'text' => 'Liczba miejsc jest ograniczona. Złóż zapytanie przez swoje konto albo napisz na accommodation@akademiata.pl.',
                'micro' => 'Po potwierdzeniu miejsca otrzymasz fakturę do wpłaty kaucji.',
            ],
        ],
    ],
    'rekr_foreign_docs_section' => [
        'watermark' => 'Documents',
        'eyebrow' => 'Dokumenty - kandydaci zagraniczni',
        'title' => 'Sprawdź wymagania dla studiów I stopnia, II stopnia i osób niepełnoletnich.',
        'tabs' => [
            [
                'label' => 'Studia I stopnia',
                'items' => [
                    'paszport albo dowód osobisty obywatela UE',
                    'wyraźna kolorowa fotografia na jasnym tle',
                    'świadectwo uprawniające do studiów wraz z suplementem i apostille',
                    'tłumaczenie świadectwa i suplementu na język polski albo angielski',
                    'dokument potwierdzający znajomość języka studiów na poziomie B2',
                    'informacja z NAWA lub inny dokument dotyczący uznania świadectwa, jeśli jest wymagany',
                    'zaświadczenie, że świadectwo uprawnia do studiów w kraju wydania, wraz z tłumaczeniem',
                    'wynik internetowego egzaminu wstępnego, jeśli dotyczy',
                    'dowód wpłaty i jego kserokopia',
                    'zaświadczenie lekarskie wyłącznie na Ochronę Środowiska',
                ],
                'note_html' => 'Dokumenty wydane na Ukrainie i Białorusi nie wymagają apostille. Przygotuj oryginały i kserokopie oraz dokumenty w liczbie wymaganej przez Biuro Współpracy Międzynarodowej.',
                'warning_html' => null,
            ],
            [
                'label' => 'Studia II stopnia',
                'items' => [
                    'dyplom ukończenia studiów wyższych wraz z suplementem i apostille',
                    'tłumaczenie dyplomu oraz suplementu na język polski lub angielski',
                    'zaświadczenie, że dyplom uprawnia do ubiegania się o przyjęcie na studia II stopnia',
                    'tłumaczenie zaświadczenia potwierdzającego uprawnienia do studiów II stopnia',
                    'decyzja dziekana, jeśli aplikujesz na inny kierunek niż wcześniej ukończony',
                ],
                'note_html' => null,
                'warning_html' => 'Na studia II stopnia nie musisz dostarczać świadectwa uprawniającego do rozpoczęcia studiów I stopnia. Jeśli zmieniasz kierunek, złóż podanie do dziekana - decyzja może zostać wydana w ciągu 30 dni roboczych.',
            ],
            [
                'label' => 'Osoby niepełnoletnie',
                'items' => [
                    'komplet dokumentów niezbędnych do przyjęcia osoby niepełnoletniej',
                    'podpis przynajmniej jednego rodzica zgodny z pisownią imienia i nazwiska w paszporcie',
                    'umowa o świadczenie usług edukacyjnych podpisana przez rodzica',
                    'zgoda opiekuna na studia w wersji polskiej albo angielskiej',
                ],
                'note_html' => null,
                'warning_html' => null,
            ],
        ],
    ],
    'rekr_residence_section' => [
        'watermark' => 'Polska',
        'eyebrow' => 'Przed przyjazdem i po przyjeździe',
        'title' => 'Wiza, karta pobytu, język i ubezpieczenie.',
        'panels_two' => [
            [
                'title' => 'Przed przyjazdem - wiza typu D',
                'text' => 'Skontaktuj się z centrum wizowym albo konsulatem RP w swoim kraju. Wiza krajowa typu D pozwala przebywać w Polsce dłużej niż 90 dni, maksymalnie przez okres jej ważności, nie dłuższy niż rok.',
                'note_html' => 'Na podstawie wizy typu D możesz także podróżować po strefie Schengen w granicach przewidzianych przepisami wizowymi.',
            ],
            [
                'title' => 'Po przyjeździe - karta pobytu',
                'text' => 'Możesz ubiegać się o zezwolenie na pobyt czasowy na okres studiów. Do wniosku potrzebujesz między innymi aktualnego zaświadczenia o kontynuacji studiów oraz potwierdzenia opłaty za studia.',
                'note_html' => 'Pierwsze zezwolenie może zostać wydane na okres do 15 miesięcy, a kolejne na okres studiów, nie dłużej niż 3 lata.',
            ],
        ],
        'panels_three' => [
            [
                'title' => 'W języku polskim',
                'text' => 'Na studia prowadzone po polsku przedstaw dokument potwierdzający znajomość języka polskiego na poziomie B2.',
            ],
            [
                'title' => 'W języku angielskim',
                'text' => 'Na studia prowadzone po angielsku przedstaw dokument potwierdzający znajomość języka angielskiego na poziomie B2.',
            ],
            [
                'title' => 'Ubezpieczenie zdrowotne',
                'text' => 'Nie jest obecnie obowiązkowe, ale uczelnia zaleca ochronę przez cały rok akademicki - polisę podróżną przed przyjazdem albo dobrowolne ubezpieczenie NFZ po przyjeździe.',
            ],
        ],
        'nawa_title' => 'Uznanie świadectwa uzyskanego za granicą',
        'nawa_text' => 'Sprawdź, czy Twoje świadectwo wymaga uznania przez NAWA lub odpowiednią instytucję. Jeżeli procedura uznania jest konieczna, przygotuj dokumenty i tłumaczenia zgodnie z obowiązującymi zasadami. Pozytywną decyzję należy dostarczyć w terminie wymaganym przez uczelnię.',
    ],
    'rekr_downloads_section' => [
        'watermark' => 'Dokumenty',
        'eyebrow' => 'Dokumenty i regulaminy',
        'title' => 'Dokumenty potrzebne podczas rekrutacji.',
        'intro' => 'W tej sekcji znajdziesz harmonogramy, regulaminy, wzory umów, zgody i formularze potrzebne podczas rekrutacji. Kliknij wybrany przycisk, aby otworzyć odpowiedni plik lub dokument.',
        'cards' => [
            [
                'title' => 'Harmonogram rekrutacji na Architekturę, Architekturę Wnętrz i Wzornictwo',
                'text' => 'Portfolio, sprawdziany i rozmowy kwalifikacyjne.',
                'cta_text' => 'Pobierz harmonogram',
                'cta_url' => 'https://chmurka.wseiz.pl/index.php/s/Bd9sE2ikPoASQr2',
            ],
            [
                'title' => 'Regulamin przyjęć na rok akademicki 2026/2027',
                'text' => 'Zasady przyjęć na studia I i II stopnia.',
                'cta_text' => 'Pobierz regulamin',
                'cta_url' => 'https://chmurka.wseiz.pl/index.php/s/pPPrHpANDRoxSMS',
            ],
            [
                'title' => 'Opłaty - Warszawa',
                'text' => 'Wysokość opłat rekrutacyjnych i opłat za studia.',
                'cta_text' => 'Pobierz dokument',
                'cta_url' => 'https://chmurka.wseiz.pl/index.php/s/LgF9TpCerLtGHb2',
            ],
            [
                'title' => 'Opłaty - Wrocław',
                'text' => 'Wysokość opłat obowiązujących kandydatów we Wrocławiu.',
                'cta_text' => 'Pobierz dokument',
                'cta_url' => 'https://chmurka.wseiz.pl/index.php/s/Jc3zWDzGwQgXPGB',
            ],
            [
                'title' => 'Studia w języku angielskim - opłaty',
                'text' => 'Informacje finansowe dla kandydatów wybierających studia po angielsku.',
                'cta_text' => 'Pobierz dokument',
                'cta_url' => 'https://chmurka.wseiz.pl/index.php/s/HafmSQsZjqdZEwg',
            ],
            [
                'title' => 'Wzór umowy - kandydaci zagraniczni',
                'text' => 'Wzór umowy o świadczenie usług edukacyjnych udostępniony dla kandydatów zagranicznych.',
                'cta_text' => 'Pobierz wzór umowy',
                'cta_url' => 'https://uczelnia.akademiata.pl/app/uploads/2023/08/Wzor-Umowy-dla-cudzoziemcow_PL_2023_2024.pdf',
                'file_note' => 'Plik PDF udostępniony na stronie rekrutacji kandydatów zagranicznych.',
            ],
            [
                'title' => 'Zgoda opiekuna - wersja polska',
                'text' => 'Dokument dla niepełnoletnich kandydatów zagranicznych.',
                'cta_text' => 'Pobierz zgodę PL',
                'cta_url' => 'https://uczelnia.akademiata.pl/app/uploads/2025/09/Zgoda-opiekuna-uczestnicy_studenci-niepelnoletni.pdf',
            ],
            [
                'title' => 'Zgoda opiekuna - wersja angielska',
                'text' => 'Guardian consent form for underage international candidates.',
                'cta_text' => 'Pobierz zgodę ENG',
                'cta_url' => 'https://uczelnia.akademiata.pl/app/uploads/2025/09/Consent-of-the-guardian-for-minors-UTA.pdf',
            ],
            [
                'title' => 'Zaświadczenie lekarskie - kandydaci zagraniczni',
                'text' => 'Wzór w języku polskim, rosyjskim i angielskim dla kandydatów na kierunek Ochrona Środowiska.',
                'cta_text' => 'Pobierz dokument DOCX',
                'cta_url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/Skierowanie_na_badania_dla_obcokrajowcow_Medical_certificate_pol-rus-eng.docx',
            ],
            [
                'title' => 'Potwierdzanie efektów uczenia się',
                'text' => 'Uchwała dotycząca organizacji potwierdzania efektów uczenia się.',
                'cta_text' => 'Pobierz uchwałę',
                'cta_url' => 'https://chmurka.wseiz.pl/index.php/s/LLyid7Ydn6HiD2p',
            ],
            [
                'title' => 'Promocje na studiach w języku polskim',
                'text' => 'Regulamin promocji dla kandydatów rozpoczynających naukę w semestrze zimowym 2026/2027.',
                'buttons' => [
                    ['text' => 'Zarządzenie 16/2026', 'url' => 'https://uczelnia.akademiata.pl/app/uploads/2026/04/ZARZADZENIE-NR-16_2026-wprowadzenia-regulaminu-promocji.pdf'],
                    ['text' => 'Załącznik nr 1', 'url' => 'https://chmurka.wseiz.pl/index.php/s/tsE4yJ8ftXGkXdf'],
                    ['text' => 'Załącznik nr 2', 'url' => 'https://chmurka.wseiz.pl/index.php/s/tK3BLLYoR52gTCN'],
                ],
            ],
            [
                'title' => 'Zniżki na studiach w języku angielskim',
                'text' => 'Dokumenty dotyczące zniżek obowiązujących w Warszawie i we Wrocławiu w roku akademickim 2026/2027.',
                'buttons' => [
                    ['text' => 'Warszawa', 'url' => 'https://chmurka.wseiz.pl/index.php/s/FwxKrLBGtgEPNcQ'],
                    ['text' => 'Wrocław', 'url' => 'https://chmurka.wseiz.pl/index.php/s/tbbQ2nTs8wtzTXH'],
                ],
            ],
            [
                'title' => 'Podanie do dziekana',
                'text' => 'Dla kandydatów na studia II stopnia zmieniających kierunek.',
                'cta_text' => 'Pobierz podanie',
                'cta_url' => 'https://chmurka.wseiz.pl/index.php/s/RYatRf3iedzXgoX',
            ],
        ],
    ],
    'rekr_contact_section' => [
        'eyebrow' => 'Kontakt i pomoc',
        'title' => 'Skontaktuj się z właściwym działem.',
        'cards' => [
            [
                'title' => 'Rekrutacja - Warszawa',
                'rows' => [
                    ['label' => 'Adres', 'value' => 'ul. Olszewska 12, III piętro, pokój 36'],
                    ['label' => 'Telefon', 'value' => '22 825 80 34<br>22 825 80 35 wew. 1'],
                    ['label' => 'E-mail', 'value' => 'rekrutacja@akademiata.pl'],
                ],
                'hours' => 'Poniedziałek: 8:00-17:00<br>Wtorek-sobota: 8:00-16:00<br>Niedziela: nieczynne',
            ],
            [
                'title' => 'Rekrutacja - Wrocław',
                'rows' => [
                    ['label' => 'Adres', 'value' => 'ul. Ostrowskiego 22, pokoje 1/2 i 1/3'],
                    ['label' => 'Telefon', 'value' => '+48 71 333 11 07'],
                    ['label' => 'E-mail', 'value' => 'rekrutacja@wab.edu.pl'],
                ],
                'hours' => 'Poniedziałek-piątek: 8:00-16:00<br>Sobota i niedziela: nieczynne',
            ],
            [
                'title' => 'Biuro Współpracy Międzynarodowej',
                'rows' => [
                    ['label' => 'Adres', 'value' => 'ul. Olszewska 12, parter, pokój 6'],
                    ['label' => 'Telefony', 'value' => '+48 22 875 30 21<br>+48 884 321 332<br>+48 783 703 709'],
                    ['label' => 'E-mail', 'value' => 'admissions@akademiata.pl<br>admissions@wab.edu.pl'],
                ],
                'hours' => 'Dyżury: poniedziałek-czwartek 9:00-16:00<br>Zapisy na miejscu: poniedziałek-piątek 8:00-14:00',
            ],
        ],
        'final_title' => 'Masz już komplet informacji?',
        'final_text' => 'Załóż konto, wybierz kierunek i rozpocznij rekrutację online.',
        'final_cta_text' => 'Rozpocznij rekrutację',
        'final_cta_url' => 'https://smartapply.akademiata.pl/',
    ],
    'rekr_faq_section' => [
        'watermark' => 'FAQ',
        'eyebrow' => 'Pytania i odpowiedzi',
        'title' => 'Najczęstsze pytania kandydatów.',
        'items' => [
            [
                'question' => 'Czy ATA wymaga konkretnych przedmiotów na maturze?',
                'answer' => 'Nie. Na większości kierunków nie ma wymogu zdawania określonych przedmiotów. Dodatkowe wymagania obowiązują na Architekturze, Architekturze Wnętrz i Wzornictwie.',
            ],
            [
                'question' => 'Czy mogę rozpocząć rekrutację przed otrzymaniem świadectwa?',
                'answer' => 'Możesz zarejestrować się i, na kierunkach bez portfolio lub sprawdzianu, zarezerwować miejsce. Przyjęcie następuje po dostarczeniu kompletnego świadectwa dojrzałości i pozostałych dokumentów.',
            ],
            [
                'question' => 'Czy dokumenty muszę złożyć osobiście?',
                'answer' => 'Kandydaci z Polski po rejestracji online umawiają wizytę i składają dokumenty osobiście. Kandydaci zagraniczni najpierw przesyłają skany, a później dostarczają oryginały i kopie.',
            ],
            [
                'question' => 'Kiedy rozpoczyna się rok akademicki?',
                'answer' => 'Rok akademicki rozpoczyna się 1 października i trwa do 30 września następnego roku. Zajęcia w semestrze zimowym mogą rozpocząć się wcześniej. Semestr letni rozpoczyna się 1 marca, a na niektórych kierunkach zajęcia mogą ruszyć w drugiej połowie lutego.',
            ],
            [
                'question' => 'Czy uczelnia posiada akademik?',
                'answer' => 'Tak. Liczba miejsc jest ograniczona. Kandydaci zagraniczni mogą złożyć zapytanie przez swoje konto albo napisać na accommodation@akademiata.pl.',
            ],
            [
                'question' => 'Czy ubezpieczenie zdrowotne jest obowiązkowe?',
                'answer' => 'Obecnie nie jest obowiązkowe, ale uczelnia zaleca ubezpieczenie obowiązujące przez cały rok akademicki na terytorium Polski.',
            ],
        ],
    ],
];
