<?php

/**
 * Default content for LP "O Uczelni" (from design mockup).
 *
 * @return array<string, array<string, mixed>>
 */
return [
	'oucz_hero_section' => [
		'title_before' => 'O',
		'title_accent' => 'Uczelni',
		'lead' => 'Jedna z najlepszych niepublicznych szkół techniczno-artystycznych w Polsce — kampusy w Warszawie i Wrocławiu, kształcenie oparte na trzech filarach: technologii, sztuce i biznesie.',
		'crumbs' => [
			['label' => 'Strona główna', 'url' => '/'],
			['label' => 'Uczelnia', 'url' => ''],
			['label' => 'O Uczelni', 'url' => ''],
		],
	],
	'oucz_subnav' => [
		'links' => [
			['text' => 'Kim jesteśmy', 'anchor' => '#kim-jestesmy', 'highlight' => 0],
			['text' => 'Nasz cel', 'anchor' => '#nasz-cel', 'highlight' => 0],
			['text' => 'Oferta edukacyjna', 'anchor' => '#oferta', 'highlight' => 0],
			['text' => 'Współpraca', 'anchor' => '#wspolpraca', 'highlight' => 0],
			['text' => 'Nasi absolwenci', 'anchor' => '#absolwenci', 'highlight' => 0],
			['text' => 'Historia filii we Wrocławiu →', 'anchor' => '#historia', 'highlight' => 1],
			['text' => 'Infrastruktura', 'anchor' => '#infrastruktura', 'highlight' => 0],
		],
	],
	'oucz_kim_section' => [
		'eyebrow' => 'Kim jesteśmy',
		'title' => 'Jedna z najlepszych niepublicznych uczelni techniczno-artystycznych w kraju',
		'badge_url' => '', // filled in fields.php via theme URI helper
		'badge_alt' => 'Ranking Perspektywy 2026 — 1. miejsce',
		'col_left' => '<p>Od 1995 roku kształcimy na studiach stacjonarnych (dziennych) i niestacjonarnych (zaocznych) — licencjackich, inżynierskich i magisterskich. Posiadamy również bogatą ofertę studiów podyplomowych oraz MBA.</p><p>Obecnie zatrudniamy ponad <b>300 specjalistów</b> z różnych dziedzin — nauczycieli-praktyków z doświadczeniem biznesowym. Nauka odbywa się w ramach trzech wydziałów: Wydziału Architektury, Wydziału Inżynierii i Zarządzania w Warszawie oraz Wydziału Wrocławskiej Akademii Biznesu w Filii ATA we Wrocławiu.</p><p>Wszystkie kierunki studiów w ATA, akredytowane przez Polską Komisję Akredytacyjną, zostały ocenione pozytywnie.</p>',
		'highlight' => '<p><b>2025 — nowa struktura Uczelni.</b> Do Akademii Techniczno-Artystycznej Nauk Stosowanych w Warszawie została włączona Wrocławska Akademia Biznesu w Naukach Stosowanych. Funkcjonuje ona dziś jako <b>filia ATA we Wrocławiu</b>, w której utworzono Wydział Wrocławskiej Akademii Biznesu. To ważny etap rozwoju, który pełniej wykorzystuje doświadczenie i zasoby obu ośrodków akademickich, otwierając przed studentami, pracownikami i partnerami biznesowymi szeroki wachlarz możliwości.</p>',
		'history_eyebrow' => 'Nasza historia w skrócie',
		'history_title' => 'Od Wyższej Szkoły Ekologii i Zarządzania do Akademii Techniczno-Artystycznej',
		'history_lede' => 'Ponad trzy dekady rozwoju: od założenia w Warszawie w 1995 roku, przez rebranding na Akademię Techniczno-Artystyczną, po utworzenie filii we Wrocławiu w 2025 roku.',
		'history_steps' => [
			[
				'year' => '1995',
				'tag' => 'Warszawa · Założenie',
				'title' => 'Wyższa Szkoła Ekologii i Zarządzania',
				'text' => 'Początek działalności w Warszawie — kształcenie na studiach licencjackich, inżynierskich i magisterskich oraz w ramach studiów podyplomowych.',
			],
			[
				'year' => '2024',
				'tag' => 'Warszawa · Rebranding',
				'title' => 'Akademia Techniczno-Artystyczna Nauk Stosowanych',
				'text' => 'Zmiana nazwy z WSEiZ na ATA podkreśla interdyscyplinarny charakter kształcenia — łączący technologię, sztukę i biznes.',
			],
			[
				'year' => '2025',
				'tag' => 'Wrocław · Rozwój',
				'title' => 'Dołączenie filii we Wrocławiu',
				'text' => 'Włączenie Wrocławskiej Akademii Biznesu tworzy filię ATA we Wrocławiu, w której powstaje Wydział Wrocławskiej Akademii Biznesu.',
			],
		],
		'logo_title' => 'Logo uczelni',
		'logo_text' => '<p>Miś w logo Wyższej Szkoły Ekologii i Zarządzania w Warszawie nie pojawił się przypadkowo. Nasi studenci często mówią, że studiują „w Misiu". To oczywiste nawiązanie do prof. dr. hab. inż. Jana Misiaka, który w 1995 roku złożył wniosek o utworzenie WSEiZ i przez wiele lat był Rektorem Uczelni. To jednoznaczny dowód, jak wielkim szacunkiem oraz renomą cieszy się założyciel Uczelni, wręcz utożsamiany z WSEiZ. Jednocześnie dało to podwaliny pod obecność Misia w naszym logo.</p><p><strong>Dlaczego możesz polegać na Misiu?</strong> To nie tylko symbol siły i odwagi, ale również tolerancji oraz umiejętności adaptacji w każdych warunkach. To także zwierzę z wyjątkową osobowością, dlatego tak doskonale pasuje do Uczelni z Charakterem, jaką jest WSEiZ.</p><p>Poza tym nikt tak jak miś nie zdaje sobie sprawy z tego, jak wiele w życiu znaczy odpowiednio długi, zdrowy sen 🙂</p>',
		'logo_image_url' => 'https://akademiata.pl/app/uploads/2025/02/Logo_ATA__wczesniej_logo.png',
		'logo_image_alt' => 'Logo Uczelni — dawne logo WSEiZ oraz obecne logo ATA, z Misiem (niedźwiedziem) obecnym w obu',
		'logo_caption' => 'Dawne logo WSEiZ i obecne logo ATA — Miś obecny w obu.',
	],
	'oucz_cel_section' => [
		'eyebrow' => 'Nasz cel',
		'title' => 'Nowoczesne i praktyczne kształcenie na potrzeby gospodarki opartej na wiedzy',
		'col_left' => 'Głównym założeniem ATA jest zapewnianie wysokiej jakości, nowoczesnego i praktycznego kształcenia studentów oraz uczestników różnorodnych form edukacji. Uczelnia przygotowuje absolwentów do skutecznego funkcjonowania w dynamicznie zmieniającym się świecie społeczeństwa informacyjnego.',
		'col_right' => 'ATA rozwija kompetencje specjalistyczne, kreatywność oraz umiejętność krytycznego myślenia, wspierając budowanie kapitału ludzkiego Polski oraz regionów związanych z warszawskim i wrocławskim ośrodkiem kształcenia. Kształci profesjonalistów wyróżniających się wiedzą, przedsiębiorczością oraz otwartością na nowe idee.',
	],
	'oucz_oferta_section' => [
		'eyebrow' => 'Oferta edukacyjna',
		'title' => 'Kierunki artystyczne, inżynierskie i biznesowe',
		'lede' => 'W Akademii Techniczno-Artystycznej Nauk Stosowanych możesz rozpocząć naukę na kierunkach artystycznych, inżynierskich oraz biznesowych. Sprawdź naszą ofertę i rozpocznij kolejny etap w swoim życiu.',
		'campuses' => [
			[
				'variant' => 'wa',
				'title' => 'Kierunki w Warszawie',
				'tag' => 'Kampus Warszawa',
				'programs' => [
					['name' => 'Architektura', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/architektura/', 'meta' => 'inż. / mgr'],
					['name' => 'Architektura Krajobrazu', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/architektura-krajobrazu/', 'meta' => 'inż. / mgr'],
					['name' => 'Architektura Wnętrz', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/architektura-wnetrz/', 'meta' => 'lic. / mgr'],
					['name' => 'Budownictwo', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/budownictwo/', 'meta' => 'inż. / mgr'],
					['name' => 'Wzornictwo', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/wzornictwo/', 'meta' => 'lic.'],
					['name' => 'Informatyka', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/informatyka/', 'meta' => 'inż.'],
					['name' => 'Mechanika i Budowa Maszyn', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/mechanika-i-budowa-maszyn/', 'meta' => 'inż.'],
					['name' => 'Ochrona Środowiska', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/ochrona-srodowiska/', 'meta' => 'inż. / mgr'],
					['name' => 'Zarządzanie', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/zarzadzanie/', 'meta' => 'lic. / mgr'],
					['name' => 'Zarządzanie i Inżynieria Produkcji', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/zarzadzanie-i-inzynieria-produkcji/', 'meta' => 'inż. / mgr'],
				],
			],
			[
				'variant' => 'wr',
				'title' => 'Kierunki we Wrocławiu',
				'tag' => 'Filia ATA · WAB',
				'programs' => [
					['name' => 'Zarządzanie', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/wroclaw-zarzadzanie/', 'meta' => 'lic. / mgr'],
					['name' => 'Architektura', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/architektura-wroclaw/', 'meta' => 'inż.'],
					['name' => 'Architektura Wnętrz', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/wroclaw-architektura-wnetrz/', 'meta' => 'lic.'],
					['name' => 'Informatyka', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/wroclaw-informatyka/', 'meta' => 'inż.'],
					['name' => 'Sprzedaż i Marketing', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/wroclaw-sprzedaz-i-marketing/', 'meta' => 'lic.'],
					['name' => 'Finanse i Rachunkowość', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/wroclaw-finanse-i-rachunkowosc/', 'meta' => 'lic.'],
					['name' => 'Turystyka i Rekreacja', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/wroclaw-turystyka-i-rekreacja/', 'meta' => 'lic.'],
					['name' => 'Komunikacja Cyfrowa i Media', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/wroclaw-komunikacja-cyfrowa-i-media/', 'meta' => 'lic.'],
					['name' => 'Logistyka', 'url' => 'https://akademiata.pl/oferta/studia-1-stopnia/wroclaw-logistyka/', 'meta' => 'inż.'],
					['name' => 'Studia podyplomowe i MBA', 'url' => 'https://akademiata.pl/studia-podyplomowe/', 'meta' => '→'],
				],
			],
		],
		'note' => 'Akademię Techniczno-Artystyczną wyróżnia ciekawa i bogata oferta edukacyjna, którą podkreśla liczba gospodarczo i społecznie ważnych kierunków studiów.',
	],
	'oucz_wspolpraca_section' => [
		'eyebrow' => 'Współpraca z otoczeniem społeczno-gospodarczym',
		'title' => 'Kształcenie ściśle powiązane z rynkiem pracy',
		'lede' => 'Ścisła współpraca z pracodawcami i przedstawicielami otoczenia społeczno-gospodarczego to jeden z kluczowych elementów rozwoju Uczelni. Ma charakter kompleksowy — obejmuje działania dydaktyczne, organizacyjne oraz projektowe. Istotną rolę odgrywają wydziałowe <b>Rady Pracodawców</b>, główna platforma dialogu między kierunkiem a rynkiem pracy.',
		'columns' => [
			[
				'title' => 'Projekty na zlecenie',
				'items' => [
					['text' => 'Modernizacja zabytkowej stajni w Wyszkowie'],
					['text' => 'Projekt modernizacji zabytkowej szkoły w Piasecznie'],
					['text' => 'Komunikacja wizualna dla miasta Wyszków'],
					['text' => 'Tor Kolarski Orzeł — inwentaryzacja i rewitalizacja'],
					['text' => 'Opracowania urbanistyczne (Piaseczno, Wawer, Konstancin)'],
					['text' => '„Miasto powodziowe" — Głuchołazy, Kłodzko'],
					['text' => 'Opakowania na racje żywnościowe dla Armii Ukraińskiej'],
				],
			],
			[
				'title' => 'Zajęcia terenowe',
				'items' => [
					['text' => 'Praktyki na budowach'],
					['text' => 'Wizje lokalne — Tor Kolarski Orzeł, Wyszków'],
					['text' => 'Zakłady oczyszczania i przetwarzania odpadów'],
					['text' => 'Warsztaty w Kampinoskim Parku Narodowym'],
					['text' => 'Stadion Legii — logistyka imprez masowych'],
					['text' => 'Muzeum Żołnierzy Wyklętych — organizacja eventów'],
				],
			],
			[
				'title' => 'Wykłady i warsztaty praktyków',
				'items' => [
					['text' => 'Cykl „Akademia Architektury"'],
					['text' => '„Dzień Młodego Architekta" — BUILDER'],
					['text' => 'Cykl „Projekt od A do Z" z absolwentami ATA'],
					['text' => '„Spotkania z Ekspertami" we Wzorcowni ATA'],
					['text' => 'Hackathon AI · cykl „ArchiSkill"'],
					['text' => 'No-code & Agenci AI · ABC social media'],
					['text' => 'Druk 3D — współpraca z Politechniką Warszawską'],
				],
			],
		],
		'partners_eyebrow' => 'Rada Pracodawców',
		'partners' => [
			['url' => 'https://uczelnia.akademiata.pl/app/uploads/2020/12/saint-gobain-logo.png', 'alt' => 'Grupa Saint-Gobain'],
			['url' => 'https://uczelnia.akademiata.pl/app/uploads/2020/12/orange-logo.jpg', 'alt' => 'Orange'],
			['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/01/hydroprojekt_LOGO.png', 'alt' => 'DHV Hydroprojekt'],
			['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/01/jeronimomartinslogo655.png', 'alt' => 'Jeronimo Martins'],
			['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/01/PSR_logo_RGB.png', 'alt' => 'Polski System Recyklingu'],
			['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/01/dom_development_nowe_logo_rgb.png', 'alt' => 'Dom Development'],
			['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/01/14618328083381aea5234c521f9ed81b8a601a39ddea6d3392cc0b.png', 'alt' => 'RICOH'],
			['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/01/warsztat-pr-logo-duze3.png', 'alt' => 'Warsztat PR'],
			['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/01/RGB_VEOLIA_HD.png', 'alt' => 'Veolia'],
			['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/01/general-electric-ge-vector-logo.png', 'alt' => 'General Electric'],
			['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/01/csm_xbs_group_241823feaa.png', 'alt' => 'XBS Group'],
			['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/01/forte.png', 'alt' => 'Forte'],
			['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/01/1200px-Kampinoski_okragle_podstawowe.png', 'alt' => 'Kampinoski Park Narodowy'],
			['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/01/logo-ilot.png', 'alt' => 'Instytut Lotnictwa'],
		],
	],
	'oucz_absolwenci_section' => [
		'eyebrow' => 'Nasi absolwenci',
		'title' => 'Wśród najlepiej zarabiających i najszybciej znajdujących pracę w Polsce',
		'badge_alt' => 'ELA — Ekonomiczne Losy Absolwentów',
		'lede' => 'Potwierdzają to wysokie miejsca w Ogólnopolskim systemie monitorowania Ekonomicznych Losów Absolwentów (ELA). Najnowszy raport dla rocznika 2024 pokazuje, że <b>6 kierunków ATA zajmuje pierwsze miejsca w Polsce</b> pod względem zarobków absolwentów w pierwszym roku po dyplomie — wyprzedzając uczelnie publiczne.',
		'ranks' => [
			[
				'variant' => '',
				'place' => '🏆 I miejsce',
				'items' => [
					['name' => 'Architektura', 'meta' => 'II stopnia · Warszawa'],
					['name' => 'Budownictwo', 'meta' => 'II stopnia · Warszawa'],
					['name' => 'Architektura Krajobrazu', 'meta' => 'I stopnia · Warszawa'],
					['name' => 'Zarządzanie i Inżynieria Produkcji', 'meta' => 'II stopnia · Warszawa'],
					['name' => 'Ochrona Środowiska', 'meta' => 'I i II stopnia · Warszawa'],
				],
			],
			[
				'variant' => 'silver',
				'place' => '🥈 II miejsce',
				'items' => [
					['name' => 'Architektura Wnętrz', 'meta' => 'I stopnia · Warszawa'],
				],
			],
			[
				'variant' => 'bronze',
				'place' => '🥉 III miejsce',
				'items' => [
					['name' => 'Finanse i Rachunkowość', 'meta' => 'I stopnia · Wrocław'],
					['name' => 'Zarządzanie', 'meta' => 'I stopnia · Warszawa'],
				],
			],
		],
		'note' => 'To obiektywne potwierdzenie, że inwestycja w edukację w ATA przekłada się na wymierne korzyści zawodowe i finansowe.',
	],
	'oucz_historia_section' => [
		'eyebrow' => 'Historia filii we Wrocławiu',
		'title' => 'Od Wyższej Szkoły Handlowej do Akademii Techniczno-Artystycznej',
		'lede' => 'Historia naszej Uczelni to historia konsekwentnego rozwoju, dostosowywania oferty edukacyjnej do zmieniających się potrzeb rynku pracy oraz budowania nowoczesnego środowiska akademickiego.',
		'steps' => [
			[
				'year' => '1997',
				'stage' => 'Etap I',
				'logo_key' => 'tl-logo-wsh.png',
				'logo_alt' => 'Logo Wyższej Szkoły Handlowej we Wrocławiu',
				'kicker' => 'Powstanie uczelni we Wrocławiu',
				'title' => 'Wyższa Szkoła Handlowa we Wrocławiu',
				'text' => '<p>Uczelnia rozpoczęła działalność jako Wyższa Szkoła Handlowa, koncentrując się na kształceniu specjalistów z obszaru biznesu, zarządzania i ekonomii. Od początku stawiała na praktyczny wymiar edukacji oraz ścisłą współpracę z otoczeniem gospodarczym.</p><p>Przez kolejne lata WSH rozwijała ofertę dydaktyczną i budowała silną pozycję wśród niepublicznych uczelni na Dolnym Śląsku. W <b>2010 roku</b> uruchomiła pierwsze studia MBA we współpracy z HHL — Leipzig Graduate School of Management, konsekwentnie rozwijając ofertę MBA oraz wyspecjalizowane studia podyplomowe (upskilling, reskilling, przebranżowienie).</p>',
			],
			[
				'year' => '2022',
				'stage' => 'Etap II',
				'logo_key' => 'tl-logo-wab.png',
				'logo_alt' => 'Logo Wrocławskiej Akademii Biznesu w Naukach Stosowanych',
				'kicker' => 'Status Akademii Nauk Stosowanych',
				'title' => 'Wrocławska Akademia Biznesu w Naukach Stosowanych',
				'text' => '<p>Po spełnieniu wymogów ustawy Prawo o szkolnictwie wyższym i nauce Uczelnia uzyskała status Akademii Nauk Stosowanych — potwierdzenie wysokiej jakości kształcenia, stabilnego rozwoju oraz dojrzałości instytucjonalnej.</p><p>Nowa nazwa — <b>Wrocławska Akademia Biznesu (WAB)</b> — lepiej odzwierciedlała nowoczesny charakter Uczelni i rozwiniętą ofertę obejmującą studia I i II stopnia, studia podyplomowe oraz programy MBA.</p>',
			],
			[
				'year' => '2025',
				'stage' => 'Etap III',
				'logo_key' => 'tl-logo-ata-wab.png',
				'logo_alt' => 'Logo Akademia Techniczno-Artystyczna, Wydział Wrocławska Akademia Biznesu',
				'kicker' => '16 lipca 2025 · Połączenie',
				'title' => 'Połączenie z Akademią Techniczno-Artystyczną',
				'text' => '<p>Kolejnym ważnym etapem było włączenie Wrocławskiej Akademii Biznesu w struktury Akademii Techniczno-Artystycznej Nauk Stosowanych w Warszawie. Proces zrealizowano 16 lipca 2025 roku, tworząc nową przestrzeń współpracy środowisk biznesowych, technicznych i artystycznych.</p><p>WAB zachowała rozpoznawalną markę, profil kształcenia i dotychczasowe doświadczenie, funkcjonując jako <b>wydział ATA</b>. Studenci zyskali dostęp do szerszej oferty, nowych kierunków rozwoju oraz większych możliwości współpracy naukowej i międzynarodowej — przy zachowaniu praktycznego, biznesowego profilu kształcenia.</p>',
			],
		],
		'note_head' => 'Kontekst · Akademia Techniczno-Artystyczna w Warszawie',
		'note_text' => 'Partnerem połączenia jest Akademia Techniczno-Artystyczna, wywodząca się z uczelni działającej od 1995 roku w Warszawie. W 2024 roku przeszła własny rebranding, zmieniając nazwę z Wyższej Szkoły Ekologii i Zarządzania na Akademię Techniczno-Artystyczną Nauk Stosowanych — podkreślając interdyscyplinarny charakter kształcenia, łączący nauki techniczne, biznesowe i artystyczne.',
	],
	'oucz_filary_section' => [
		'eyebrow' => 'Jedna historia, trzy filary przyszłości',
		'title' => 'Nowoczesna, wielokampusowa Uczelnia oparta na trzech filarach',
		'pillars' => [
			['num' => '01', 'variant' => 'p1', 'title' => 'Technologia', 'text' => 'Dostęp do kompetencji przyszłości — narzędzi cyfrowych, sztucznej inteligencji, automatyzacji i innowacyjnych metod pracy.'],
			['num' => '02', 'variant' => 'p2', 'title' => 'Sztuka', 'text' => 'Rozwój kreatywności, wrażliwości projektowej, estetyki i komunikacji oraz umiejętności tworzenia rozwiązań funkcjonalnych i odpowiedzialnych społecznie.'],
			['num' => '03', 'variant' => 'p3', 'title' => 'Biznes', 'text' => 'Połączenie wiedzy z praktyką, przedsiębiorczością, zarządzaniem oraz realnymi potrzebami organizacji i rynku.'],
		],
	],
	'oucz_infra_section' => [
		'eyebrow' => 'Infrastruktura',
		'title' => 'Nowoczesna baza dydaktyczna',
		'lede' => 'Uczelnia dysponuje nowoczesną, przystosowaną do potrzeb osób z niepełnosprawnościami bazą dydaktyczno-administracyjną w Warszawie i we Wrocławiu. Wybierz budynek, aby rozwinąć jego opis i galerię zdjęć.',
		'buildings' => [
			[
				'open' => 1,
				'name' => 'Budynek przy ul. Olszewskiej 12',
				'loc' => 'Warszawa · Mokotów',
				'text' => 'Główna siedziba administracyjna Uczelni. Budynek ma bogatą historię: w okresie międzywojennym mieściła się tu fabryka „Młot" produkująca barierki, sejfy i konstrukcje metalowe, a po 1945 roku drukarnia wojskowa. Po przebudowie i rozbudowie zrealizowanej przez Archimed Sp. z o.o. administracja Uczelni przeniosła się do niego w listopadzie 2013 roku.',
				'facts' => [
					['text' => 'Rektorat oraz Dziekanaty Wydziałów Architektury i Inżynierii i Zarządzania'],
					['text' => 'Sala Senatu, Kwestura, Dział Jakości, Nauczania i Badań'],
					['text' => 'Biuro Współpracy Międzynarodowej'],
					['text' => 'Biuro Karier'],
					['text' => 'Pracownie projektowe'],
					['text' => 'Wypożyczalnia sprzętu dla studentów z niepełnosprawnościami'],
				],
				'gallery' => [
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/IMG_0201.jpg', 'alt' => 'Budynek Olszewska 12 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/IMG_0204.jpg', 'alt' => 'Budynek Olszewska 12 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/IMG_0206.jpg', 'alt' => 'Budynek Olszewska 12 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/IMG_0208.jpg', 'alt' => 'Budynek Olszewska 12 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/IMG_0291.jpg', 'alt' => 'Budynek Olszewska 12 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/IMG_0297.jpg', 'alt' => 'Budynek Olszewska 12 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/IMG_0303.jpg', 'alt' => 'Budynek Olszewska 12 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/IMG_0311.jpg', 'alt' => 'Budynek Olszewska 12 — wnętrze'],
				],
			],
			[
				'open' => 0,
				'name' => 'Budynek przy ul. Grójeckiej 128',
				'loc' => 'Warszawa · Ochota',
				'text' => 'Budynek dydaktyczny z zapleczem wykładowym i pracowniami projektowymi, wykorzystywany m.in. przez kierunki architektoniczne i projektowe.',
				'facts' => [
					['text' => '2 audytoria (po 160 miejsc)'],
					['text' => '2 sale wykładowe (po 70 miejsc)'],
					['text' => '4 sale do ćwiczeń audytoryjnych (po ok. 35 miejsc)'],
					['text' => 'Pracownie Rysunku i Malarstwa'],
					['text' => 'Pracownie Projektowania Architektonicznego'],
					['text' => 'Pracownie Grafiki Komputerowej i Projektowania Mebli'],
					['text' => 'Stolarnia wraz z makieciarnią'],
				],
				'gallery' => [
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/001.jpg', 'alt' => 'Budynek Grójecka 128 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/002.jpg', 'alt' => 'Budynek Grójecka 128 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/008.jpg', 'alt' => 'Budynek Grójecka 128 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/009.jpg', 'alt' => 'Budynek Grójecka 128 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/010.jpg', 'alt' => 'Budynek Grójecka 128 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/011.jpg', 'alt' => 'Budynek Grójecka 128 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/012.jpg', 'alt' => 'Budynek Grójecka 128 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/xF1.jpg', 'alt' => 'Budynek Grójecka 128 — wnętrze'],
				],
			],
			[
				'open' => 0,
				'name' => 'Kompleks budynków przy ul. Rejtana 16',
				'loc' => 'Warszawa · Mokotów',
				'text' => 'Rozbudowany kompleks dydaktyczny z pełnym zapleczem wykładowym, laboratoryjnym i projektowym. Budynek dawniej mieścił odlewnię czcionek; w 2015 roku odsłonięto tablicę pamiątkową upamiętniającą osoby związane z jego historią z okresu II wojny światowej.',
				'facts' => [
					['text' => '5 auli wykładowych'],
					['text' => '12 sal do ćwiczeń audytoryjnych'],
					['text' => '4 pracownie komputerowe'],
					['text' => 'Laboratoria: fizyczne, chemiczne, gleboznawstwa, biologii, zoologii, botaniki i geologii'],
					['text' => 'Pracownia Projektowania Wirtualnego Obiektu Budowlanego i Krajobrazu (iMac, tablety graficzne, manipulatory 3D)'],
					['text' => 'Pracownie fotografii, rysunku, grafiki komputerowej i rzeźby'],
					['text' => 'Galeria sztuki, biblioteka i czytelnia'],
				],
				'gallery' => [
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/fot-2-1-scaled-e1618468176646.jpg', 'alt' => 'Kompleks Rejtana 16 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/03.jpg', 'alt' => 'Kompleks Rejtana 16 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/04.jpg', 'alt' => 'Kompleks Rejtana 16 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/05.jpg', 'alt' => 'Kompleks Rejtana 16 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/O_II_02.jpg', 'alt' => 'Kompleks Rejtana 16 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/O_I_05.jpg', 'alt' => 'Kompleks Rejtana 16 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2022/02/IMG_2718-scaled.jpg', 'alt' => 'Kompleks Rejtana 16 — wnętrze'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2022/02/DSCF3435.jpg', 'alt' => 'Kompleks Rejtana 16 — wnętrze'],
				],
			],
			[
				'open' => 0,
				'name' => 'Nieruchomości przy ul. Klaudyńskiej 33',
				'loc' => 'Klaudyn-Laski k. Warszawy',
				'text' => 'Działka o powierzchni ok. 3,5 ha z zespołem budynków o łącznej powierzchni 720 m² (budynek dwukondygnacyjny 380 m², pawilon ogrodowy 110 m², pawilon naukowo-dydaktyczny 230 m²). Mieści się tu Terenowa Stacja Ochrony Przyrody i Krajobrazu ATA, wspierająca zajęcia z architektury krajobrazu, architektury wnętrz, budownictwa i ochrony środowiska. Obiekt służy też studenckim wydarzeniom integracyjnym.',
				'facts' => [
					['text' => '4 sale wykładowo-projektowe (20–30 miejsc)'],
					['text' => '2 pracownie rysunku i malarstwa'],
					['text' => 'Laboratoria: oczyszczania ścieków, utylizacji odpadów, projektowania krajobrazu'],
					['text' => 'Laboratoria: meteorologii i klimatologii, monitoringu środowiska, mechaniki gruntów'],
					['text' => 'Pracownia komputerowa'],
					['text' => 'Własna oczyszczalnia ścieków'],
				],
				'gallery' => [
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/klaudyn-laski-049.jpg', 'alt' => 'Klaudyńska 33 — teren i budynki'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/klaudyn-laski-053.jpg', 'alt' => 'Klaudyńska 33 — teren i budynki'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/klaudyn-laski-061.jpg', 'alt' => 'Klaudyńska 33 — teren i budynki'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/klaudyn-laski-073.jpg', 'alt' => 'Klaudyńska 33 — teren i budynki'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/klaudyn-laski-079.jpg', 'alt' => 'Klaudyńska 33 — teren i budynki'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/klaudyn-laski-082.jpg', 'alt' => 'Klaudyńska 33 — teren i budynki'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2021/03/klaudyn-laski-094.jpg', 'alt' => 'Klaudyńska 33 — teren i budynki'],
					['url' => 'https://uczelnia.akademiata.pl/app/uploads/2022/02/fot-1-scaled.jpg', 'alt' => 'Klaudyńska 33 — teren i budynki'],
				],
			],
			[
				'open' => 0,
				'name' => 'Filia ATA we Wrocławiu — ul. Ostrowskiego 22',
				'loc' => 'Wrocław · Wydział Wrocławska Akademia Biznesu',
				'text' => 'Siedziba filii ATA we Wrocławiu, w której działa Wydział Wrocławskiej Akademii Biznesu — kontynuator wieloletniej tradycji Wyższej Szkoły Handlowej i Wrocławskiej Akademii Biznesu. Nowoczesny, wielokondygnacyjny budynek dydaktyczny w dogodnej lokalizacji w południowej części Wrocławia stanowi zaplecze kształcenia na kierunkach biznesowych, informatycznych i projektowych.',
				'facts' => [
					['text' => 'Sale wykładowe i ćwiczeniowe'],
					['text' => 'Pracownie komputerowe'],
					['text' => 'Pracownie projektowe (architektura, architektura wnętrz)'],
					['text' => 'Biblioteka i przestrzenie do pracy własnej'],
					['text' => 'Zaplecze dla studiów podyplomowych i MBA'],
					['text' => 'Adres: ul. Ostrowskiego 22, 53-238 Wrocław'],
				],
				'gallery' => [
					['url' => '', 'alt' => 'Filia ATA we Wrocławiu — budynek z szyldem Akademia Techniczno-Artystyczna', 'theme_key' => 'infra-wroclaw-1.jpg'],
					['url' => '', 'alt' => 'Filia ATA we Wrocławiu — widok z lotu ptaka', 'theme_key' => 'infra-wroclaw-2.jpg'],
					['url' => '', 'alt' => 'Budynek filii we Wrocławiu — elewacja', 'theme_key' => 'infra-wroclaw-3.jpg'],
				],
			],
		],
	],
	'oucz_closing_section' => [
		'title_before' => 'To połączenie',
		'title_accent' => 'technologii, sztuki i biznesu',
		'title_after' => 'stanowi o sile nowej Uczelni',
		'text' => 'Dzięki synergii tych trzech obszarów studenci zyskują nie tylko wiedzę akademicką, ale przede wszystkim przewagę kompetencyjną — uczą się myśleć analitycznie, działać twórczo i podejmować skuteczne decyzje w dynamicznym środowisku zawodowym.',
		'cta_primary_text' => 'Poznaj naszą ofertę',
		'cta_primary_url' => '#oferta',
		'cta_secondary_text' => 'Wróć do historii',
		'cta_secondary_url' => '#historia',
	],
];
